### ISSUE TITLE
Replace references of GitLab to GitHub in the code.

### ISSUE THREAD

**Issue by jb3** [python-discord/site#145]
As of now the codebase links to things such as https://gitlab.com/python-discord/projects/site. We need to change all instances of GitLab to GitHub.

We will also need to rewrite the GitLab documentation on site to GitHub for the next code jam.

**Comment by lemonsaurus** [comment]
yes thank you I did that 10 hours ago you nerd. #90

**Comment by jb3** [comment]
yes

**Comment by lemonsaurus** [comment]
in truth, your branch may be more thorough.

**Comment by jb3** [comment]
you are the rightful owner of the issue though, when I get back on my laptop I'll close my pull request and if you want you can merge anything from that branch in.

**Comment by lemonsaurus** [comment]
This was solved like, back when I was still a young man.
