### ISSUE TITLE
Django: Add Bulma to the repo.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#158]
Since we're using Bulma, and we'll need to customize it, we'll need access to it in our project.

Either we have to npm install it (which adds another step for our contribs), or we just clone it, copy all the files over into the project, and keep it there. This makes it hard to update, should we ever want to do this.

A third option might be something like having it as a submodule or a git dependency, but these options seem less attractive to me. However, feel free to discuss them in this issue.

**Comment by gdude2002** [comment]
I think it's quite likely that we're going to need to use Node again for stuff like JS linting and minifying, so it might be the best way to handle this as well. That said, I'm not sure how it'd integrate into the toolchain - I guess we'd have to figure out some scripts.

**Comment by jchristgit** [comment]
We could add it as a regular Django app with static files similiar to the crispy thing. That way, it integrates with the pip workflow, the `collectstatic` command works with it, and we can use it easily through the templating engine.

**Comment by lemonsaurus** [comment]
@jchristgit you mean by simply putting the files into the repo? or is there some other method I'm not familiar with?

**Comment by jchristgit** [comment]
In this repo? No, an extra repo with a single Django app (as in, a *django app*, not a *django* (pause) *app*) in it, where the app would then contain `static/bulma/...`.

**Comment by lemonsaurus** [comment]
okay, but then it needs to be on pypi or something if we're gonna add it the way we're adding crispy. is that what you mean?

**Comment by jchristgit** [comment]
Sorry for the late reply. Yeah, I guess we could also install it from GitHub though.

**Comment by lemonsaurus** [comment]
weird comment to leave at this point, since https://github.com/python-discord/django-simple-bulma solves this problem completely and we should obviously use that :hilarious_emoji:

**Comment by jchristgit** [comment]
crispy chicken bulma django merged https://github.com/python-discord/site/pull/198
