### ISSUE TITLE
Django: Bulma-Extensions

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#160]
We'll want stuff like sliders, dividers and calendars, so we'll probably want Bulma-Extensions.

Get it set up in the repo. This ticket is blocked by #158.

See https://wikiki.github.io/

**Comment by lemonsaurus** [comment]
This is now solved with our new pypi package https://github.com/python-discord/django-simple-bulma. We just need to import it and set it up to solve this issue.

**Comment by jchristgit** [comment]
implemented by the simple super simple supersonic bicycle man https://github.com/python-discord/site/pull/198 merged
