### ISSUE TITLE
Wiki Still Has Gitlab Pages and Icons

### ISSUE THREAD

**Issue by MrHemlock** [python-discord/site#172]
Looking through our wiki, we still have a lot of links and icons that are GitLab related.  We need to go in and clean that up.  The pages that stood out to me first were the Project Guide pages.

**Comment by jb3** [comment]
This probably isn't a good first issue considering that wiki editing is only allowed by Helpers+ right, now, anyone from the helper team is welcome to take a stab at it though.

**Comment by MrHemlock** [comment]
Yeah, it's why I didn't add that tag in the first place.

**Comment by lemonsaurus** [comment]
pretty sure this has been solved at this point. either way it's not really relevant anymore because we will definitely not be moving any references to gitlab over to the new wiki.
