### ISSUE TITLE
Structure and layout of Django rewrite.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#176]
Currently, the Django branch uses the standard structure that Django will generate for you, and that the official tutorial uses. Here's an example of its layout:

![image](https://user-images.githubusercontent.com/2098517/51353096-dbc17b00-1aaf-11e9-8036-1ec9522cd54e.png)

Parts of the page are separated into what Django calls "apps", so that `API` is an app and `home` is an app and `wiki` is an app. The project itself has a folder called `pysite` with project-wide settings and url forwards, and each app has a folder named after the app, which contains everything relevant to that app. Static files, templates, urls, views, and migrations, and so on.

In Django books like Two Scoops of Django, it is made clear that this does not scale well. A large project may have dozens of apps, and keeping a folder for each of them in the root level gets messy really quick. It also means you'll soon have dozens of static folders, dozens of templates folders, and so on.

Based on some recommendations from these books and from looking at major projects like the pycon website and edx, I've come up with a suggestion for how I think we could lay this project out.

```
root/
├── docker/
├── site/
│   ├── apps/
│   │   ├── __init__.py
│   │   ├── api/
│   │   │   ├── migrations/
│   │   │   ├── tests/
│   │   │   └── views/
│   │   │       └── health_check_view.py
│   │   └── home/
│   │       ├── migrations/
│   │       ├── tests/
│   │       └── views/
│   │           └── faq.py
│   │           └── landing.py
│   ├── static/
│   │   └── home/
│   │       ├── js/
│   │       ├── img/
│   │       └── scss/
│   ├── staticfiles/
│   │   ├── js/
│   │   ├── img/
│   │   └── scss/
│   ├── templates/
│   │   ├── home/
│   │   │   ├── faq.html
│   │   │   └── landing.html
│   │   ├── base.html
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
├── .flake8
├── .gitignore
├── manage.py
├── README.md
├── LICENSE
└── ...
```

At the root level, we have everything that pertains to the repo itself. CI stuff, docker stuff, linter stuff, and so on. Everything else is inside of a folder called site. settings are split into multiple files, apps kept in an apps folder, and all templates as well as all static files are dumped in a single folder, and separated by subfolders. templates that are used across multiple apps are kept in the templates folder itself, such as `base.html`

Migrations and tests are still in their app folders, because it's nice to have all the python that relates to each app in one place.

This is just a suggestion, and I'm hoping we can have a conversation about this and come up with a good structure, ideally one that doesn't have so much folder bloat.

**Comment by lemonsaurus** [comment]
A closer look at an app folder with todays system. Note that templates are kept in `appname/templates/appname/` so that you can call them with `{% extends "appname/template.html" %}`, since Django will load all these folders in and behave as if all their contents are all in the same folder.

![image](https://user-images.githubusercontent.com/2098517/51353808-f399fe80-1ab1-11e9-89da-8aff5815a16d.png)

**Comment by lemonsaurus** [comment]
was hoping this would generate a little bit more conversation.

**Comment by AnonGuy** [comment]
What's the difference between `static` and `staticfiles` in your example? Is `staticfiles` for things like css that applies to all templates?
```
│   ├── static/
│   │   └── home/
│   │       ├── js/
│   │       ├── img/
│   │       └── scss/
│   ├── staticfiles/
│   │   ├── js/
│   │   ├── img/
│   │   └── scss/
```
It seems like folder bloat to me, but I'm not so experienced with Django so feel free to correct me. Maybe static files that are used globally should be just under `static/global`, and static files for specific apps should go under respective subfolders?
```
│   ├── static/
│   │   └── global/
│   │       ├── js/
│   │       ├── img/
│   │       └── scss/
│   │   └── home/
│   │       ├── js/
│   │       ├── img/
│   │       └── scss/
```

**Comment by lemonsaurus** [comment]
Okay, it's been 23 days.

I'm suggesting we change the folder structure to the following, based on the arguments laid out above:
```
root/
├── docker/
├── docs/
├── log/
├── site/
│   ├── apps/
│   │   ├── __init__.py
│   │   ├── api/
│   │   │   ├── migrations/
│   │   │   ├── tests/
│   │   │   └── views/
│   │   │       └── health_check_view.py
│   │   └── home/
│   │       ├── migrations/
│   │       ├── tests/
│   │       └── views/
│   │           └── faq.py
│   │           └── landing.py
│   ├── static/
│   │   └── home/
│   │       ├── js/
│   │       ├── img/
│   │       └── scss/
│   ├── staticfiles/
│   │   ├── js/
│   │   ├── img/
│   │   └── scss/
│   ├── templates/
│   │   ├── home/
│   │   │   ├── faq.html
│   │   │   └── landing.html
│   │   ├── base.html
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
├── .flake8
├── .gitignore
├── manage.py
├── README.md
├── LICENSE
└── ...
```

I'd like to see at least a single comment on this issue before I go ahead and make a pull request. I believe this would be a far more intuitive folder layout, with far less folder bloat.

Todays structure has 11 folders in the root, my structure would cut this in half, or even lower.

Todays path for the landing page would be `home/templates/home/landing.html`, with my structure it would be `site/templates/home/landing.html`. 

With todays structure, there are multiple duplicate template and static folders, while with the above structure all our static and template files would be found in the same folder.

Todays structure has project-related files such as docker, CI and linting, in the same folder as all the site-related files. My structure separates the two clearly by putting everything related to the site inside a parent folder named `site`. This folder already exists today, as `pysite`, but in my scheme it serves a more useful function.

Todays structure has app folders (like `api` or `wiki`) in the root folder along with all the other unrelated stuff like `docker` or `.venv`. My structure collects all app folders inside of a folder named `apps`, which scales much better.

**Comment by xanderyzwich** [comment]
I think that this is a great idea!

**Comment by MarkKoz** [comment]
@heavysaturn Can you provide insight as to why the static and template folders would be split off from the apps? Is it not more convenient to have all files pertaining to a given app under a single subdirectory? Is this done because it's nice to have all Python code separate from the rest, because having all static or template files near by is more convenient, or some other reason?

**Comment by lemonsaurus** [comment]
my reasoning for that is simply to keep the app folders as lean as possible. When you put a static folder inside of an app, your static file paths end up something like this:
`/site/apps/main_page/static/main_page/logo.png`

With my system, you'd have something like this instead:
`/site/static/main_page/logo.png`

I think this is far more intuitive to find, and far less clumsy to refer to. The downside is that the apps aren't as "self-contained" as they might have been had all the migrations and static files and templates been kept in the app folder as well, but this argument (although very frequently seen) feels kind of nebulous to me, as we're not really trying to (and probably won't be able to) make apps that can be lifted out of our site and slotted into other websites, we're just trying to make parts of a single whole.

**Comment by MarkKoz** [comment]
I honestly don't have hard feelings about this either way. The inconsistency just struck me: going from an `app/thing_type/` structure and reversing it to `thing_type/app/`.

**Comment by lemonsaurus** [comment]
it's the double `main_page` in `/site/apps/main_page/static/main_page/logo.png` that gets me. I find it really inelegant.

**Comment by jchristgit** [comment]
implemented as of https://github.com/python-discord/site/pull/198
