### ISSUE TITLE
Django: Show coverage in pull requests and badge on README

### ISSUE THREAD

**Issue by jchristgit** [python-discord/site#185]

**Comment by sco1** [comment]
Badge is actioned by https://github.com/python-discord/site/commit/2cbc302f3bea9e3930859b644cdf093ee8973e99

For "coverage in pull requests" do you mean a GH bot integration?

**Comment by jchristgit** [comment]
my memory fails me what I meant originally, but since we require 100% coverage anyways, this is not needed.

**Comment by scragly** [comment]
Oh, my bad, I didn't realise there was a relevant issue for the shields when I pushed that. I should have checked, sorry!
