### ISSUE TITLE
Event Calendar for Community Events

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/site#188]
We're really putting some effort in organizing community events and our event calendar is taking shape. I think it's time to think about a proper event calendar on our website, that includes things like:

- Our seasonal events;
- Code jams;
- Esoteric challenges;

Obviously, we're still talking about other types of events as well, which should ultimately be included.

Feature-wise, I think it would be interesting to be able to filter the events by type and make those filters linkable. That way, you can link someone to the code jam events schedule or the seasonal event schedule.

**Comment by RohanJnr** [comment]
where will the data load from for the calender?
Should i make a modelform to add events?
can u give me some implimentation details plz

**Comment by Den4200** [comment]
Related to #417

**Comment by lemonsaurus** [comment]
This is no longer relevant now that Discord has an event calendar.
