### ISSUE TITLE
Endpoint for Raffle Cog

### ISSUE THREAD

**Issue by sco1** [python-discord/site#189]
To support https://github.com/python-discord/bot/issues/326, the API needs endpoints to add/remove and randomly select user(s) from the running raffle.

**Comment by atmishra** [comment]
If you can add more details on this, I would like to pick this.

**Comment by scragly** [comment]
@atmishra It appears you've not yet contributed to our org before, so welcome. I've accepted you to work on another task for now (https://github.com/python-discord/bot/issues/535), so I'm going to leave this one open for others until that's complete.

**Comment by atmishra** [comment]
Hi @scragly did my first contribution to python-discord/bot and my PR got merged. I want to continue contributing, can I take this now?

**Comment by scragly** [comment]
Hi @atmishra, sorry for the delay, you're welcome to take on this ticket if you like. Let me know if you're okay to work on it and I'll assign you to it.

**Comment by sco1** [comment]
This will be implemented bot-side only (https://github.com/python-discord/bot/issues/326)
