### ISSUE TITLE
Replacing poetry with pipenv in the Django branch

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/site#193]
During the most recent staff meeting (2019-03-24, see https://github.com/python-discord/organisation/blob/master/staff-meetings/20190324-minutes-staff-meeting.MD) we've decided not to continue our move to Poetry for dependency management. 

As a consequence, the Django branch of site needs to migrated to pipenv instead of poetry.

**Comment by jchristgit** [comment]
fixed through https://github.com/python-discord/site/pull/198
