### ISSUE TITLE
Superstar endpoint isn't working for forced nicks.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#196]
When providing the optional forced_nick parameter when doing superstar, this makes the API respond with something that is not JSON.

![image](https://user-images.githubusercontent.com/2098517/55295306-cd76d000-540b-11e9-8e54-e41263673ea4.png)

Please investigate and fix.

**Comment by jchristgit** [comment]
With the new Django website there is no longer support for explicit nickname specifications. Is it worth fixing this?

**Comment by lemonsaurus** [comment]
might be better to just remove the feature from the bot? it's not like we've ever really used it.

**Comment by lemonsaurus** [comment]
or.. is it already removed for the django branch of the bot, maybe? @jchristgit

**Comment by jchristgit** [comment]
it's removed yes

**Comment by jchristgit** [comment]
@lemonsaurus

**Comment by lemonsaurus** [comment]
yeah then this is pointless.
