### ISSUE TITLE
Django: Wiki

### ISSUE THREAD

**Issue by gdude2002** [python-discord/site#200]
Issue #142 states that the wiki should be moved entirely to GitHub, but the decision has since been made to integrate a wiki with the new Django site.

We will be using [django-wiki](https://github.com/django-wiki/django-wiki) for this task, and we'll customize its templates so that it integrates with the rest of the site.

Before doing this, setting up the basic site templates is probably a good idea.

**Comment by lemonsaurus** [comment]
This has been merged in.
