### ISSUE TITLE
Web REPL

### ISSUE THREAD

**Issue by GhostofGoes** [python-discord/site#210]
Currently, the bot is able to execute small Python snippets. This would expand on that by hosting a live Python interpreter REPL on the site. While there are other web-based Python REPLs out there, it might be beneficial to host our own to provide a known-good non commercial resource. We could also add collaboration/helper tools in the future, such as a live view of a session, shared sessions, and pastebin integration (or just saving code on our site).

**Comment by jb3** [comment]
This is not something we will be pursuing on site as it doesn't mesh with the goals of the site going forward. Existing services work for this (i.e. repl.it) and work well (albeit most are commercial).
