### ISSUE TITLE
Django: Change the wiki dependency back to the official package

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#214]
We've temporarily created a fork of `django-wiki` to quickly add support for Django 2.2. We've also created a PR at https://github.com/django-wiki/django-wiki/pull/951 with the exact same changes as we have in our fork.

If our PR is merged, or if the maintainers of `django-wiki` add Django 2.2 compatibility on their own, we change the pipfile so it points back at the official package rather than at our fork.

**Comment by Den4200** [comment]
Dewikification makes this issue no longer relevant.
