### ISSUE TITLE
Offensive word filtering

### ISSUE THREAD

**Issue by jerbob** [python-discord/site#222]
Once the bot's word filters are triggered, we will need to call a site endpoint to store the ID of the offending message, along with a "delete time" of one week after the authored time.

The bot will pull a list of offending message IDs daily, and delete the messages that have reached the allotted delete time.

This feature will be worked on after the Django rewrite is complete.

**Comment by jerbob** [comment]
The corresponding bot issue for this feature can be found [here](https://github.com/python-discord/bot/issues/364).

**Comment by jchristgit** [comment]
We do not need to store a timestamp, we can compare by snowflake.

**Comment by lemonsaurus** [comment]
@jchristgit is there a convenient method available to our django site for converting a discord snowflake into a timestamp? The idea is that we need to know when one week has passed.

**Comment by jchristgit** [comment]
Yes, Discord IDs contain their creation time in the timestamp:


![](https://learning-csharp.might-be-super.fun/2b93ba.png)


For instance, to cast ID -> datetime:

```py
>>> def snowflake_to_datetime(snowflake: int) -> int:
...     since_epoch = snowflake >> 22
...     as_unix_ms = (since_epoch + 1420070400000) / 1000  # 124.. is the epoch
...     return datetime.fromtimestamp(as_unix_ms)
...
>>> bolt_id = 252908391075151874
>>> snowflake_to_datetime(bolt_id)
datetime.datetime(2016, 11, 28, 22, 27, 39, 243000)
```

In the database, this would then just translate to selecting all entries with an ID greater than what we want to look at.

**Comment by lemonsaurus** [comment]
linked to https://github.com/python-discord/bot/issues/364, assigning both to @Akarys42
