### ISSUE TITLE
Merging useful `master` commits into `django` before the switchover

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#228]
The `django` branch is 151 commits behind `master`. This means that we will need to look through those 151 commits and see if there's something useful that we need to bring with us into the `django` branch before we switch over.

When viewing commit history, GitHub will display 35 commits per page. This means that we just need to look through five pages of commits. A great number of these will be easy to just disregard based on the commit message. We don't need to look at commits that are merging master into a branch, and we can disregard anything related to our resources page (we're just gonna grab the latest version of that page for Django anyway). 

What we _should_ port over to django is stuff like API bugfixes, changes to tools (like the precommit fixes we did), our sponsor button ... stuff like that.

**Comment by sco1** [comment]
Here's some of the obvious things I've noticed on a first pass. This list ignores any backend related changes, as these are assumed to be handled, and anything already mentioned in Lemon's post.

- [x] `pre-commit` (w/correct `.pre-commit-config.yaml`)
- [x] Updated `flake8` linting rules
- [x] Contributor Guide
- [x] Github's `FUNDING.yml`
- [x] Clean up `site`'s 8 million branches

A draft PR for these minor changes has been created: https://github.com/python-discord/site/pull/229. Contributors can also push changes directly to the PR's source branch.

**Comment by lemonsaurus** [comment]
I've looked through the 151 commits now, and found the following:

- [x] [A change to the superstar JSON list, to fix Lil' Joseph.](https://github.com/python-discord/site/commit/99e6f9aa3a04381311cd2d4b87377674b24b6d12) When checking if the django branch had this change, I realized the django branch doesn't have the JSON at all. I'm not sure how superstar is supposed to work without it, so I've reached out to @jchristgit for clarification.

  ELA edit: Superstarify logic [is moved to the bot](https://github.com/python-discord/bot/blob/django/bot/cogs/superstarify/stars.py)

- [x] [A hotfix for the deleted message part of the API](https://github.com/python-discord/site/commit/75779893867e6be42834320ba51aab2e2b7bbd62). When checking if the `django` branch had this change, I realized the `django` branch has no view for this at all. This will need to be implemented or it will break a lot of stuff.
- [x] References to the snake API. This is no longer necessary. I've pushed a commit to the Draft PR to remove all references to snakes from the `django` branch.
- [x] [strftime style durations for the duration parser](https://github.com/python-discord/site/commit/87af3a48fecfc3973f7c247160465c252fea4a9b). I don't understand how this works in the django branch, the code this was added to doesn't exist there at least. I've asked @jchristgit for clarification.

  ELA edit: This is implemented in bot as a [converter](https://github.com/python-discord/bot/blob/django/bot/converters.py#L261)

- [x] [Improvements to the off-topic name API, like allowing apostrophes](https://github.com/python-discord/site/commit/11ef65e877e8da47c7d9ee2bc1986d69d695c53d). We've also had changes recently that will allow UPPERCASE and !? characters. From what I can tell, these changes do not exist in the `django` branch. 

- [x] Update privacy policy 6d9b28005ca5a2b65986899f84b03e1ff5294927 0bb2f4ee2cbe10f8224c6021227c1cce42c625db d1400320e5a162fd9ec891101cc281ea23454039

Most of these should probably be spun off into separate issues. These findings indicate we are nowhere near as done with the API as I thought.

**Comment by MarkKoz** [comment]
@lemonsaurus 
> We've also had changes recently that will allow UPPERCASE and !? characters. From what I can tell, these changes do not exist in the django branch.

Were you talking about python-discord/bot@5e16f4a52d59c73a04323e070e7b4a320e8c1e49? Looks to be a bot-only change that needs to be made (which was merged into bot's django branch already).

**Comment by lemonsaurus** [comment]
I was under the impression changes would be needed in both repos, but if we're sure that is not the case, then it looks like we're good. :thumbsup:

**Comment by lemonsaurus** [comment]
I've cleaned up all the branches on both `site` and `bot`. I think this issue is complete.

**Comment by MarkKoz** [comment]
@lemonsaurus The last two on the list still haven't been implemented. Am I missing something?
