### ISSUE TITLE
Migrating nominations/watches to the new database

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/site#233]
As discussed briefly during the staff meeting, both the nominations and the Big Brother watches need to be migrated to the new database. Since the format of both types of watches have changed, we need to migrate the data to the new format.

### Old database format
- Stored as shadow warns (notes)
- Reason for the nomination is stored in the `reason` field, prefixed with `Helper nomination: `
- Reason for ending the nomination is stored in the `reason` field, prefixed with `Unwatched (talent-pool): `

### New database format
- Each nomination is stored as a row in the Nominations table
- The row has separate fields for the reason for the nomination and the reason for ending the nomination.

### Old database format
- Stored as shadow warns (notes)
- Reason for the watch is stored in the `reason` field, prefixed with `bb watch: `
- Reason for ending the watch is stored in the `reason` field, prefixed with `Unwatched (big-brother): `

### New format
- Stored as "watch" type infractions in the Infractions table
- The reason for watching is stored in the `reason` field;
- The end reason is stored in the `reason` field of a separate `watch` row with the prefix `Unwatched: `. (Since there's not separate field available for unwatch reasons in the infractions table.)

**Comment by lemonsaurus** [comment]
This should be solved by updating the `djangoify` repo to support this conversion. See https://github.com/python-discord/djangoify/issues/1. Maybe @SebastiaanZ and @jchristgit can sync on this and cooperate to get it done?
