### ISSUE TITLE
Django: Syntax highlighting not working on code blocks.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#243]
On pages like https://django.pythondiscord.com/pages/asking-good-questions/, we don't have working python syntax highlighting. Let's get that working before we launch the site.

**Comment by gdude2002** [comment]
Just seems like you're missing the CSS for it. If you wanted to use one of the standard styles...

`pygmentize -S <STYLE> -f html -a .codehilite > <STYLE>.css`

* [List of styles](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/styles/)

**Comment by lemonsaurus** [comment]
Solved in 0300c02
