### ISSUE TITLE
Django: Write tests for the ReminderViewSet

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#244]
We currently don't have any tests for this ViewSet. It still has 100% coverage because it doesn't implement any custom methods, but we should still be testing if the endpoint provides the functionality that we expect.

**Comment by bendiller** [comment]
I'd love to work on this if it's open. Seems like a good introductory issue for me.

**Comment by MarkKoz** [comment]
Sure

**Comment by Den4200** [comment]
Already done.
