### ISSUE TITLE
Django: Code Jam pages

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#246]
We need Code Jam pages, as in, pages that present the results of previous Code Jams, on the new website. @scragly is on the job.

**Comment by AvianAnalyst** [comment]
Something following the same sort of layout as : https://pythondiscord.com/pages/code-jams/code-jam-2/ or were you thinking something different?

**Comment by lemonsaurus** [comment]
Something similar to that, yes, but this issue is going to be difficult for you to work on because we don't have any way for you to log in and be able to edit these pages (only Core Devs have access so far). These are wiki pages, not static pages.

There's some more information about how these pages should be set up, but, it's on a private repo that's used by staff so the URL will 404 for you.

The relevant issue can be found here: https://github.com/python-discord/organisation/issues/66

it has tons of information about those previous code jams, and even some pictures.

**Comment by Den4200** [comment]
This seems to be finished.
