### ISSUE TITLE
Site header covers toolbar in wiki editor when fullscreen

### ISSUE THREAD

**Issue by kosayoda** [python-discord/site#256]
The website article editor currently looks like this:
![image](https://user-images.githubusercontent.com/41782385/65371093-ac908880-dc92-11e9-83a8-dc5ed351a911.png)

When Side-by-Side or Fullscreen is toggled, the sitewide header covers the toolbar, making it impossible to revert to regular editing by mouse or access any of the buttons on the toolbar.

![image](https://user-images.githubusercontent.com/41782385/65371119-ed889d00-dc92-11e9-9f5f-75bdb0e956db.png)

Only tested on the latest Firefox on Linux, as I don't have current access to other browsers or operating systems.

**Comment by Den4200** [comment]
Dewikification makes this no longer relevant.
