### ISSUE TITLE
Docker Compose: web service does not wait for Postgres to be ready

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/site#259]
It leads to [such](https://paste.pydis.com/avuxawosod.py) errors. Notice that Postgres reports it's ready to accept connections after the web service has already failed. Docker has an [article](https://docs.docker.com/compose/startup-order/) on some approaches we could take to prevent this from happening. What should we go with?

**Comment by lemonsaurus** [comment]
This was addressed in https://github.com/python-discord/site/pull/265.
