### ISSUE TITLE
Numbered list in wiki markdown resets after markup between elements.

### ISSUE THREAD

**Issue by kosayoda** [python-discord/site#262]
Raw text in editor:
---

````
1. Clone your forked repository using `git clone` followed by your fork's Git URL.
```
$ git clone https://github.com/kosayoda/seasonalbot
```
2. Once cloned, change your working directory to the repository:
```
$ cd seasonalbot
```
````
Intended output:
---
1. Clone your forked repository using `git clone` followed by your fork's Git URL.
```
$ git clone https://github.com/kosayoda/seasonalbot
```
2. Once cloned, change your working directory to the repository:
```
$ cd seasonalbot
```

---

Actual output:
---
1. Clone your forked repository using `git clone` followed by your fork's Git URL.
```
$ git clone https://github.com/kosayoda/seasonalbot
```
1. Once cloned, change your working directory to the repository:
```
$ cd seasonalbot
```

---

Note the reset in the numbering, 1. -> 1.
PS: Can't upload the screenshot because of GitHub issues so the example is slightly unclear.

**Comment by Den4200** [comment]
Dewikification makes this no longer relevant.
