### ISSUE TITLE
Move tests to a single tests/ folder

### ISSUE THREAD

**Issue by gdude2002** [python-discord/site#290]
As discussed on Discord, we currently have tests for each app placed within the app's directory - but this leaves us without a clean place to test things like utils, which aren't unique to the app.

Instead, all tests should be moved to `pydis_site/tests`, with a subfolder for each app - much like we did with the templates and static files.

**Comment by ju-sh** [comment]
I'll give a shot at this.

**Comment by scragly** [comment]
This is still in active discussion and we're not yet decided if this is something we're going to do. 

As a note for future @ju-sh, it's best to wait for a reply and to be assigned by an org member before going ahead with any PRs.

**Comment by gdude2002** [comment]
Sorry, that's my bad. I was given the go-ahead to apply the `good first issue` label before a discussion prompt came up, and I forgot to apply the `discussion` label at that point.

**Comment by Xithrius** [comment]
The stance on this as of now is that there doesn't seem to be a large pushing reason to do this change, even after 2 years.

If someone really wants to implement this, then this issue can be re-opened.
