### ISSUE TITLE
OAuth2 redirect url is broken for pydis.com

### ISSUE THREAD

**Issue by tagptroll1** [python-discord/site#306]
https://cdn.discordapp.com/attachments/635950537262759947/641296190545068056/unknown.png

https://discordapp.com/oauth2/authorize?client_id=409107086526644234&redirect_uri=https%3A%2F%2Fpydis.com%2Faccounts%2Fdiscord%2Flogin%2Fcallback%2F&scope=identify+email&response_type=code&state=N37TCTVst2WE 

logged in from pydis.com

pythondiscord.com seems to work

**Comment by gdude2002** [comment]
This probably should never work for the sake of simplicity. `pydis.com` and friends should most likely redirect to `pythondiscord.com` and friends, or vice-versa, otherwise you're going to have two entirely separate sets of cookies.

**Comment by scragly** [comment]
Tbh, having pydis.com 301 to pythondiscord.com is not just a good fix for this, but it also makes our website setup more simple and has been something @lemonsaurus suggested when I was touching things last, so I'd consider that a suitable fix and worth doing sooner than later.

**Comment by scragly** [comment]
This is now actioned.
