### ISSUE TITLE
Further account system improvements

### ISSUE THREAD

**Issue by gdude2002** [python-discord/site#307]
A few additional things have come up that could be worked on RE the account system.

- [ ] Expose linked accounts via the API, so the bot can get at them (eg, GH accounts)
- [ ] Close button on the account settings modal
- [ ] Match up role colours on the account settings modal labels
- [ ] Close mobile navigation when modal is opened (this currently soft-locks the page!)

**Comment by ks129** [comment]
Is this still planned as OAuth2 will be removed from site?

**Comment by jb3** [comment]
That's a good point. None of these things will be relevant post-dewikification.

We may integrate GitHub (or generic external OAuth2) with the forms app to capture accounts when filling in forms.
