### ISSUE TITLE
Track usage of off topic names to better distribute name usage.

### ISSUE THREAD

**Issue by scragly** [python-discord/site#309]
Currently off topic names are used randomly, however randomness is pretty far from evenness. It would be nice to make use of names more evenly, to avoid recently used names being used multiple times.

One method would be to have a column tracking usage in the current iteration, a bool of True/False. `used=False` would be the default for new names. The pool of available names to pick from will be all tags with `used=False`. When a names it picked, it'll be given `used=True`. Once no names are returned for `used=False`, we just update the used column for all to be set to False again and start over again.

**Comment by ikuyarihS** [comment]
Should we instead store the number of times tags have been used and use that as the weights ( max - current ) so unused tags have more chance to be used? That way we can have a nice chart of tags and its usage as well.

**Comment by scragly** [comment]
It's possible the original issue description wasn't clear as I for some reason was saying "tags" instead of "names", which is my bad, and partially because I was talking about tags at the same time as writing this up lol.

Since this is for offtopic names, there's no nice chart to be had, since usage would be distributed evenly.

**Comment by ikuyarihS** [comment]
Ah I see, thank you for the clarification. If we only want every name to be used evenly then yes I agree, a column of True / False will be much lighter, and can easily guarantee every name will be used until reset.

**Comment by ks129** [comment]
Can I work on this?
