### ISSUE TITLE
Error page improvements

### ISSUE THREAD

**Issue by jb3** [python-discord/site#31]
- [x] Close window by hitting "x"
- [x] Make error header darker
- [x] Link issue tracker instead of displaying link

**Comment by lemonsaurus** [comment]
https://pythondiscord.com/error/510 breaks. we should test all the codes.

**Comment by jb3** [comment]
I'm led to believe that's the internals of flask and that we can't really do much about it, for example, 402 also fails with some socket error.

**Comment by jb3** [comment]
Regarding the issue with the broken status codes, upon looking at the error again it seems that werkzeug does not have an error for that specific status code.
```py
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/home/joseph/Python/site/pysite/views/main/error.py", line 12, in get
    return abort(code)
  File "/usr/lib/python3.6/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/werkzeug/exceptions.py", line 686, in __call__
    raise LookupError('no exception for %r' % code)
LookupError: no exception for 600
Thu Mar  1 14:56:23 2018 {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '48168', 'HTTP_HOST': 'pysite.local:8080', (hidden keys: 25)} failed with LookupError
```
I'm going to treat this as not an issue with our implementation, this isn't an issue at all really, the few codes that are documented in RFC and exist do not mean anything to us, I know for a fact we won't have to use `Not Extended` or `Payment required` at any point on our application.

**Comment by jb3** [comment]
All enhancements of error pages now complete and in production. Closing issue.
