### ISSUE TITLE
Add star table, API endpoints, admin views for Superstarify.

### ISSUE THREAD

**Issue by scragly** [python-discord/site#311]
Related: https://github.com/python-discord/bot/issues/662

In order to allow the superstarify pool of stars to be added into the database, we'll need to define a table schema, the endpoints we'll interact with and the admin view to define for interacting with it on the website admin interface.

The table will require at least:
- star_name
- image_url

We need to be able to do the following via the api:
- fetch data of a random star
- add a new star
- edit a star
- delete a star

**Comment by ks129** [comment]
Is anyone already working on this (and bot side) or not (I want a little rest from tic-tac-toe... 😅 )?

**Comment by MarkKoz** [comment]
What's the justification for adding an API for it? It seems overcomplicated. Why can't we keep it local on the bot in a JSON file? The convenience of being able to add or remove stars on the fly doesn't strike me as particularly useful.

**Comment by MarkKoz** [comment]
Turns out we decided not to use the API but these issues were never updated to reflect that decision. I'm closing this issue as this should be purely a bot side implementation.
