### ISSUE TITLE
Wiki previews have stopped loading.

### ISSUE THREAD

**Issue by scragly** [python-discord/site#314]
![image](https://user-images.githubusercontent.com/29337040/69637243-fc7d3880-10a3-11ea-9a3d-2f24822a8cdb.png)

Web console has:
```
Refused to display 'https://pythondiscord.com/pages/guides/_preview/' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('SAMEORIGIN, DENY'). Falling back to 'deny'.
```

Will need to look into seeing what's up with this one. Might be related to nginx settings yet and have nothing to do with the code.

**Comment by MarkKoz** [comment]
This has been fixed a while ago.
