### ISSUE TITLE
Patreon webhook relay

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#316]
## What do we want?
We want notifications in the #meta channel whenever someone pledges to our Patreon account, or when someone increases their pledge from one dollar amount to another.

**Whenever this happens, a webhook in the channel should post something like this:**

[@some_user](https://nothing) has pledged $3 to the Python Discord Patreon. This brings our total income up to **$42 per month**! [random compliment], [@some_user](https://nothing)!

All the money donated to our Patreon goes towards prizes for the many events we run throughout the year, such as our Advent of Code event, our Hacktoberfest event, and our bi-annual Code Jams. If you'd like to become a Patron, please visit https://www.patreon.com/python_discord.

## How do we do that?
Well, [Patreon allows us to create webhooks](https://docs.patreon.com/#webhooks) which can let us know when pledges happen. It also has [an API (which even has a PyPI package)](https://docs.patreon.com/#api-libraries) which can be used to fetch additional information if neccessary (maybe the total donation amount?)

The problem is, we can't implement the webhook directly into our discord channels because they simply are not compatible with the format that Discord supports.

So, we should create an endpoint on the site which can receive these webhooks from Patreon, then we'll pull the data out of the webhook (or the API, if necessary) needed to display the above message, and then we'll call a Discord webhook endpoint for the #meta channel to relay the information in the correct format.

## Wait, what did you mean by [random compliment]?
Make a fun list of random compliments somewhere and we'll insert a different one each time this happens. Here's a few examples of what I mean:
- You're a superstar
- You're a million dollars
- I will remember this day for the rest of my life
- We're BFFs now
- You're the reason I get up in the morning
- I'm glad I met you
- You're my favorite
- I bet your code is beautiful

## What if someone abuses that endpoint?
Yeah, that's probably gonna happen, so to prevent that we need a bit of security for it. This endpoint should require some sort of API key, which should be appended to the URL as a parameter. It's important we use parameters and not JSON for this, because we won't be able to control what Patreon sends us with its webhooks, but we can control which URL it sends it to.

This API key should be checked against an environment variable (something like `PATREON_WEBHOOK_RELAY_KEY`, which a member of our DevOps team will generate and put in our salt pillar. That way, only someone with this key will be able to use the relay.

**Comment by ks129** [comment]
@lemonsaurus I have some question/notes about this:

1. Can I work on it?
2. About security: In Patreon webhooks documentation is:
> By creating a webhook, you can specify a URL for us to send an HTTP POST to when one of these events occur. This POST request will contain the relevant data from the user action in JSON format. It will also have headers
>
> `X-Patreon-Event: [trigger]`
> `X-Patreon-Signature: [message signature]`
>
> where the message signature is the HEX digest of the message body HMAC signed (with MD5) using your webhook's secret viewable on the webhooks page. You can use this to verify us as the sender of the message.
So my idea is to use `X-Patreon-Signature` for verification.
3. Environment variables: I think this should have 2 new environment variables: `DISCORD_PATREON_WEBHOOK_URL`, to where will be processed result sent and `PATREON_SECRET` (+ other keys when required) that will be used to identify a request.
4. Storage: We should storage Patreons information in DB when the user has Discord connected to there. In bot side, we should add `!patreon` command to see general Patreon stats and `!patreon members|users|supporters` command that fetch information from DB and show users.

**Comment by lemonsaurus** [comment]
> Can I work on it?

Yes, but get an approval from @scragly first, because I seem to remember scrags claiming it at some point, a while back.

> So my idea is to use X-Patreon-Signature for verification.

That seems reasonable.

> Environment variables: I think this should have 2 new environment variables: DISCORD_PATREON_WEBHOOK_URL, to where will be processed result sent and PATREON_SECRET (+ other keys when required) that will be used to identify a request.

Yep, sounds good.

> Storage: We should storage Patreons information in DB when the user has Discord connected to there. In bot side, we should add !patreon command to see general Patreon stats and !patreon members|users|supporters command that fetch information from DB and show users.

Hmm, I'm not sure about this one. I can discuss it with the other core devs and see what they think, but I don't really wanna store this user information if we don't have a very good reason to. On the other hand, a simple `patreon` command that shows number of patrons and dollars might still be a good thing to have, but would be an entirely separate thing and out of scope for this issue.

**Comment by scragly** [comment]
> I seem to remember scrags claiming it at some point, a while back.

It's mostly that I mentioned we don't need it to be a site thing. Instead a simple reactor event on our linode would suffice; at least, assuming there's no extra features required. 

> a simple patreon command

I don't this is necessary. They'd have a role in-server, so we'd easily be able to see patreon counts by doing a role member count instead in the case someone asks, but it's not often they do and they can just look at the page if they wish anyhow if so. At any rate, as stated by lemon, it's not in scope of this issue either. 

For now, I'd suggest against implementing this capability in site.

**Comment by lemonsaurus** [comment]
Okay, in that case, I'm closing this issue and we'll handle this in saltstack. I've opened a ticket here: https://github.com/python-discord/salt/issues/18
