### ISSUE TITLE
Make dropdowns in admin sorted by displayed value and searchable

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/site#318]
May need something like [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light/) to make them searchable. Otherwise trying to create records from the admin site is practically useless with thousands of users.

An even neater feature would be to allow specifying an ID too.

**Comment by lemonsaurus** [comment]
I can't imagine this is still relevant. We don't really use the admin interface in our site anymore, so let's close this.
