### ISSUE TITLE
Move docs to wiki and document testing and creating migrations

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/site#321]
## Move docs

- [ ] Migrate [deployment](https://github.com/python-discord/site/blob/master/docs/deployment.md) docs to a new sub-article.
    - [ ] Check how relevant they still are (ask the author, @jchristgit)
    - Deployment docs are low priority.
- [ ] Migrate [configuration](https://github.com/python-discord/site/blob/master/docs/configuration.md) docs to a new table in the environment variables section.

## Tests

- [ ] Document how to run tests.
- [ ] Possibly document how to write tests. See python-discord/bot#716 for more details.

## Migrations

- [ ] Document how to create migrations and when new ones are necessary.
- [ ] Document how to name migrations well rather than using the automatically generated names.
- [ ] Document how to deal with conflicts i.e. new migrations from upstream.

## Other

- [ ] Document how to re-build the Docker image in case dependencies are changed.

**Comment by lemonsaurus** [comment]
This is no longer relevant. Most of the documentation mentioned here is already quite good in the official Django docs (like how to make migrations), and some of the stuff that's referred to (like `deployment.md`) no longer exists in this repo. This probably made sense two years ago, but I don't think it makes sense now.
