### ISSUE TITLE
Truncate Verbose Infraction Reason Strings

### ISSUE THREAD

**Issue by sco1** [python-discord/site#323]
Currently, the `bot` paginator raises a `RuntimeError` if the string it's attempting to paginate exceeds the defined page size:

```py
def add_line(self, line: str = '', *, empty: bool = False) -> None:
    """
    Adds a line to the current page.
    If the line exceeds the `self.max_size` then an exception is raised.
    This function overrides the `Paginator.add_line` from inside `discord.ext.commands`.
    It overrides in order to allow us to configure the maximum number of lines per page.
    """
    if len(line) > self.max_size - len(self.prefix) - 2:
        raise RuntimeError('Line exceeds maximum page size %s' % (self.max_size - len(self.prefix) - 2))
```
([src](https://github.com/python-discord/bot/blob/33dd712d3fe046c196ac0d31e0bfaf121f469ed5/bot/pagination.py#L58-L69))

While this generally hasn't been an issue, it causes problems when presenting an infraction history that contains verbose reason strings. The bot is unable to provide the infraction history at all until the offending infractions are identified & edited.

To mitigate this issue, infraction reason strings returned by the API should be truncated if their length exceeds a specified threshold (`500` characters?) and, if truncated, add a suffix indicating that this has occurred (`<...>` ?).

**Comment by RohanJnr** [comment]
Why can't this be done on the bot side?

**Comment by sco1** [comment]
It's a pretty trivial site-side implementation and a non-trivial bot-side implementation.

**Comment by MarkKoz** [comment]
We ended up doing it bot-side in https://github.com/python-discord/bot/pull/981.
