### ISSUE TITLE
Remove the collapse/expand arrow from navbar mobile view

### ISSUE THREAD

**Issue by MrHemlock** [python-discord/site#327]
Currently in mobile view (or small width screens), the "More" section of the navbar still shows a non-functional collapse/expand arrow that we should probably remove.
![](https://cdn.discordapp.com/attachments/411200599653351425/674629734453215242/unknown.png)

**Comment by priyanshu0405** [comment]
Hey @MrHemlock , can I take this issue? Thanks!!
