### ISSUE TITLE
Docker related errors page cannot be opened

### ISSUE THREAD

**Issue by F4zii** [python-discord/site#328]
![image](https://user-images.githubusercontent.com/44242259/74594422-fe212180-503e-11ea-9b1f-3fa49ee4ecbc.png)
While clicking on the link above, I encountered the following problem - 
![image](https://user-images.githubusercontent.com/44242259/74594432-185aff80-503f-11ea-8f87-33b3770b9bc7.png)

**Comment by MarkKoz** [comment]
Thanks. I fixed by using a normal URL. Turns out the `wiki:` style only works with markdown (the fancy yellow box is done with HTML).

**Comment by F4zii** [comment]
Thanks Mark!
