### ISSUE TITLE
manage.py logs disappear after collectstatic

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/site#329]
For example, the messages printed in `create_superuser()` and `"Starting server."` in `run_server()` don't show despite the web server still running just fine.

**Comment by scragly** [comment]
It seems to be related to the python logging module thinking it's running similar to a service instead of through a standard terminal when run within a docker container. By adding the config line `tty: true` to the development compose file, logging seems to work as expected again.

**Comment by scragly** [comment]
As a note, this can possibly impact any docker development environments in which we rely on the python logging module, so we may need to review other projects' dev compose files also to add the configuration line.
