### ISSUE TITLE
Intercept Azure webhooks and relay them to Discord with an accessible URL

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/site#338]
By default, the webhooks sent by Azure use a link which requires an authorised account to access. If the site intercepts the webhook, modifies the field for the URL, and sends it back out again, developers will be happier and more productive!

Here is the URL the webhook currently uses:

https://dev.azure.com/python-discord/web/build.aspx?pcguid=a4900c06-bea4-4b1b-930f-7bd7a2e05a22&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f6105

A more accessible URL for the same build is:

https://dev.azure.com/python-discord/Python%20Discord/_build/results?buildId=6105

[Here](https://docs.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#build.complete) is the documentation of the Azure webhook payload.  `message.markdown` and `detailedMessage.markdown` are _probably_ the relevant fields.

**Comment by SebastiaanZ** [comment]
We're no longer using Azure, so this issue can be closed. The GitHub Action workflow webhooks are not perfect either, but that's worth a separate discussion is less related to the issue here.
