### ISSUE TITLE
Bleach security alert

### ISSUE THREAD

**Issue by eivl** [python-discord/site#340]
let's upgrade bleach since dependabot could not do it for us. 
But we might have some dependencies that require this version of bleach. 

Pipfile.lock
```
    "bleach": {
            "hashes": [...],
            "version": "==2.1.4"
```

changes that are needed.

```
bleach = ">=3.1.1"
```

I'm unaware of how to fix dependabot, that might also be a solution to this issue. 

Here are the messages that dependabot gives us.

![image](https://user-images.githubusercontent.com/132364/76311595-9c687600-62d1-11ea-80be-0c27d4ff238e.png)

![image](https://user-images.githubusercontent.com/132364/76311574-8c509680-62d1-11ea-8fd8-f205ada6b0a6.png)

**Comment by eivl** [comment]
After some discussion in dev-core. 
The problem lies with `django-wiki` so we can dismiss the alert or upgrade to 0.6-beta

We cant upgrade to a pre-release without allowing all dependencies to also upgrade to pre-releases. So, for now, we will ignore the alert, it does not affect us as we do not use bleach anymore.

**Comment by lemonsaurus** [comment]
I think we can probably just close this. We'll update django-wiki in the future, but I've dismissed the alert.
