### ISSUE TITLE
Replace Allauth anti-email monkey-patch with proper settings.

### ISSUE THREAD

**Issue by scragly** [python-discord/site#341]
The allauth extension we use for the discord login and connection to a github account for any of our site accounts.

We have a [monkeypatch](https://github.com/python-discord/site/blob/master/pydis_site/apps/home/apps.py#L17-L38) to avoid saving in our database any email details that we may get from oauth authorisations. This does not avoid the request for emails showing in the auth request page though, as the scope is still requested.

Instead, we can define in settings.py the appropriate provider settings, particularly any required scopes to be requested. If we only provide `identify` for the discord one, it won't add the `email` scope in the auth request page in future, making it a cleaner and more appropriate solution.

The setting would look like:
```py
SOCIALACCOUNT_PROVIDERS = {
    'discord': {
        'SCOPE': [
            'identify',
        ],
    }
}
```

The relevant scope setting for github can be given also, it just needs to be looked up as to what scopes we should restrict it to in order to avoid unnecessary sensitive data being stored.

**Comment by jb3** [comment]
The note on the [privacy page](https://pythondiscord.com/pages/privacy/) needs removing once we have got a PR merged for this.

**Comment by Akarys42** [comment]
This is what is probably causing the sentry issue [SITE-6](https://sentry.io/organizations/python-discord/issues/1539211531/?referrer=github_integration)

**Comment by jb3** [comment]
SITE-6 is not caused by this as far as I know. It is caused when you 
manually visit the OAuth2 callback URL without the information from Discord.

**Comment by Akarys42** [comment]
Well, yes, but from what I could gather on the Internet, the page is still supposed to be visited without any issue. 

Since the traceback message is `Reverse for 'account_email' not found.` and this view is supposed to be managed by AllAuth, I think this is causing it.
