### ISSUE TITLE
Python Logo on Top-Left looks Squashed

### ISSUE THREAD

**Issue by robertt** [python-discord/site#35]
The Python logo in the top left looks a bit squashed. I dont know if its just me or something but its triggering my OCD

**Comment by jb3** [comment]
If on mobile device this is fixed on mobile-optimisation branch

**Comment by robertt** [comment]
ok dank but merge with master plox

**Comment by lemonsaurus** [comment]
This has already been merged in. Can we verify that it has solved the issue? @Haxified1

**Comment by lemonsaurus** [comment]
Closing this since there's no answer.
