### ISSUE TITLE
Deleted role mention on the Contributing page

### ISSUE THREAD

**Issue by F4zii** [python-discord/site#351]
### Description
This role mention is supposed to be ```@PyDis Core Developers``` if im not wrong.
![image](https://user-images.githubusercontent.com/44242259/78533025-e3725a00-77f0-11ea-8efe-2656ef5a736e.png)

**Comment by Akarys42** [comment]
I feel like this statement could just be `ask in #dev-contrib`, because some of the non-core dev can also answer questions

**Comment by F4zii** [comment]
Will do

**Comment by F4zii** [comment]
This issue is now fixed, closing this..

**Comment by Akarys42** [comment]
My though was about writing "feel free to ask in the #dev-contrib channel in the server. We're always happy to help", if I misspoke, I apologize. :smiley:

**Comment by F4zii** [comment]
@Akarys42  Oh no worries about that, I discussed about that issue there, then was told to change it myself
