### ISSUE TITLE
Create robots.txt file

### ISSUE THREAD

**Issue by Lvl4Sword** [python-discord/site#354]
Python Discord staff tend to check terms of service and robots.txt to see if a site can be scraped.
I feel it'd be wise to implement a robots.txt file for the Python Discord site to lead by example.

**Comment by MarkKoz** [comment]
What would we put in it? Do we want to let people scrape our site? I would say yes, if our infrastructure can handle the load (I don't foresee it being high). I think it'd be beneficial for people to be able to use our site if they're learning web-scraping. On the other hand, there are already websites made for this, so we don't necessarily have to take up that burden too.

**Comment by jb3** [comment]
Our infrastructure most definitely can handle the load, if we experience issues with repeated spam we can look into ratelimiting certain clients.

**Comment by Kronifer** [comment]
what would have to be done to do this?

**Comment by HassanAbouelela** [comment]
It should be quite simple on django. Add a URL for `robots.txt` which returns a basic text response. The response will depend on the consensus of this issue, but it mostly seems to be:
```md
User-agent: *
Allow: *
```

It may be wise to block certain routes, such as admin, but that requires more discussion.

**Comment by Kronifer** [comment]
alright, sounds good!

**Comment by hedyhli** [comment]
Hi, `/robots.txt` returns 404 so I'm assuming it isn't added yet. Can I work on this please?

**Comment by whispersofthedawn** [comment]
> Hi, `/robots.txt` returns 404 so I'm assuming it isn't added yet. Can I work on this please?

Hi, this was discussed here https://github.com/python-discord/site/pull/586#issuecomment-940710000 and it was decided that a worker would be used.

**Comment by ChrisLovering** [comment]
Yea, the worker pr is here https://github.com/python-discord/workers/pull/13

**Comment by hedyhli** [comment]
> > Hi, `/robots.txt` returns 404 so I'm assuming it isn't added yet. Can I work on this please?
> 
> Hi, this was discussed here [#586 (comment)](https://github.com/python-discord/site/pull/586#issuecomment-940710000) and it was decided that a worker would be used.

Ah ok, the PR didn't link this issue so I didn't see that. Thanks!

**Comment by Akarys42** [comment]
Closed in favor of python-discord/workers#13
