### ISSUE TITLE
Youtube Push Notifications in Discord.

### ISSUE THREAD

**Issue by RohanJnr** [python-discord/site#367]
# About
Have notification/video link+details posted in discord when a YouTuber uploads a video. Here the YouTubers can be those that make content related to python, a specific field(web dev), etc. A few notable examples are Corey MS, Traversy Media, FreeCodeCamp, JustDjango, CodingEntrepreneurs, etc.

## Implementation

This can be achieved using YouTube Data API (v3) which supports push notifications via PubSubHubbub. 
(**[Link](https://developers.google.com/youtube/v3/guides/push_notifications)**)

We will make use of the Django rest framework to set up a callback URL that accepts a POST request.
The data received is then parsed, processed, and then sent to a discord channel by executing a discord webhook.
(**[Link](https://discord.com/developers/docs/resources/webhook#execute-webhook)**)

### Steps

1. Setup a callback URL to accepts a POST and GET request.
 - Why do we need to accept a GET request?
   - While subscribing for push notifications, a GET request is sent to the callback URL with a few parameters and one such parameter which is sent is `hub.challenge` which has to be sent back as a response to complete the verification process. Once the verification process is done, we will start receiving POST requests whenever that YouTuber uploads a video.

2. Parse incoming POST request data.
The data will be in `atom feed` (similar to XML) and cannot be parsed directly(as far as I know). The data should be decoded to string and then parsed using the built-in XML lib or [defusedxml](https://pypi.org/project/defusedxml/) lib.

3. Process and gather necessary information from the data like the YouTube Channel Name, link to the video, title, etc.

4. Finally, send it as a message to discord by executing a webhook.

## Examples
Here is the code which I wrote for my website to achieve the same(Its not the most polished code but as a reference, it works).
https://github.com/RohanJnr/YNBWebsite-Django/blob/production/ynb_site/apps/api/views.py

Here is the same but implemented in the bottle framework.
https://github.com/nicolaskenner/youtube-push-notifications/blob/master/youtube_push_notifications.py

**Comment by MarkKoz** [comment]
I like this feature in theory, but I do worry the frequency of videos posted may be too high. I think this would be particularly problematic with tutorial videos. I question if they're really even worth posting - they're not something people would casually watch. Does anyone have ideas for YouTube channels that would fit this well? Some good topics may be conference talks, tips and tricks, Python community news (but in video format), and going over cool projects/demos created in Python. Honestly, I don't watch many programming videos so I'm not familiar with what's out there. Before we can go ahead with the implementation, we need to evaluate if we can effectively make use of this feature.

**Comment by RohanJnr** [comment]
Sorry for being late,
I feel tutorials could be a great choice for notification. Channel examples:
 - Corey MS
Python programming tutorials.
- Traversy Media
Mostly related to JS, but also covers other languages too (this channel has kinda become a replica of freecodecamp now).
- coding For Entrepreneurs 
This one is my favorite. Great Django and python tutorials. Recently uploaded 30 days of python series.
- JetBrains TV
IDE related and python tutorials occasionally.

The above-mentioned channels are the ones which I usually follow.
This page mentions more YouTubers who make content related to python.
https://realpython.com/python-youtube-channels/

I feel tutorials indulge a sense of curiosity in a person when he/she has never heard of the library/module/stuff thought in the video.
Most of these channels don't really make tutorials on basic python (by this, I mean beginner stuff), instead, the tutorials are mostly of libraries or unique projects.

Also, it would be cool if the content in not python restricted (just a mere suggestion).

**Comment by lemonsaurus** [comment]
We've looked over this in a site issue review meeting among the core devs today.

We're going to close this, partially because it's quite old without seeing any interest, secondly because we don't think it belongs in the `site`. If we decide we want something like this later, it seems like a good candidate for CloudFlare Workers.
