### ISSUE TITLE
User's role field needs to have a cascade delete

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/site#369]
#357 replaced the FK with an `ArrayField`. This introduced a problem of the roles table falling out of sync with the users table. I encountered an issue when trying to sync a user with the bot. One of their roles had been deleted from the roles table, but it was still present in their roles field. The validator ensures all roles exist in the table, so the request was failing.

Apparently [Django Postgres Extensions](https://django-postgres-extensions.readthedocs.io/en/latest/arrays.html) have a solution for this.

**Comment by MarkKoz** [comment]
Django Postgres Extensions doesn't seem to be maintained any more and may be incompatible with Django 3.0.

**Comment by D0rs4n** [comment]
I believe, as a temporary workaround (until the migration to FastAPI) this could be solved by using a `pre_delete` signal, that unassigns the Role assigned to the User's ArrayField, then performs the process as usual.
(That's purely a suggestion, I faced the same issue in a previous code jam)
