### ISSUE TITLE
Make the user endpoint more scalable

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#375]
Right now, we're syncing users in a hugely inefficient way. When we request the users, we get a giant 90,000 item reply, and when we send users we're sending them one at a time with 90,000 requests.

Let's not do either of these things.

This will be a cross-platform change, so see the corresponding bot issue here.

## Use DRF pagination
On the User endpoint, enable [DRF pagination](https://www.django-rest-framework.org/api-guide/pagination/) and send something like 10000 items at a time.

This will break the bot requests, so on the bot side, we'll need to implement proper handling of this pagination.

## Allow batch updates
If we POST a batch of users to this endpoint, we the endpoint should add all of these users as a single query. This is also supported by DRF, [so have a look at this part of the documentation](https://www.django-rest-framework.org/api-guide/serializers/#dealing-with-multiple-objects) for instructions on how to implement it.

**Comment by RohanJnr** [comment]
I would like to try this one

**Comment by RohanJnr** [comment]
Am I supposed to write tests for the implemented changes or will there be a seperate issue for that?

**Comment by lemonsaurus** [comment]
Currently the site requires 100% test coverage, so yes you will have to write and adjust tests.

By the way, it seems like we may already support bulk input in this endpoint - see the BulkSerializerMixin that we use in the serializer. So it might only be pagination that's required.

I was planning to handle this issue myself, but if you're confident you can handle it you're welcome to it.
