### ISSUE TITLE
Dewikification: Create an app for showing event info.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#385]
**Remember to target the `dewikification` branch with this pull request**

For displaying event information (like for our code jams), we will want a slightly different approach. These will basically just be normal static pages, but we need a clever, modular system for displaying sidebars.

## What's a sidebar?
Take a look at one of our current event pages.
![image](https://user-images.githubusercontent.com/2098517/92273501-c64ece00-eeeb-11ea-953a-e95c3c3fbaee.png)

See the information on the right hand side? That's a sidebar. These sidebars should be able to contain lists, hyperlinks, images, any content at all.

Most of our pages have sidebars that contains some images and then some links, like this:
![image](https://user-images.githubusercontent.com/2098517/92273597-f1d1b880-eeeb-11ea-888f-40065302c286.png)

So we need a nice, modular, DRY way of doing this.

## Do I add all the pages that are currently on the site?
No. This will be handled in another issue.

## Wait, so should these pages be markdown too or what's the deal?
No no. That's just for the guides. For the event pages, we very often need stuff like YouTube embeds, custom bulma components, and so on. So we want the full power of Django Templating Language for building these pages, but just with a clever drop-in component for sidebars.

**Comment by ks129** [comment]
Can I get assigned to it?

**Comment by ks129** [comment]
Good way to add sidebars is with dictionaries that contains data, but as Django own template language don't allow creating variables, then we need Jinja2 as template engine for this app in order to create variables. This should be added as secondary engine.

**Comment by lemonsaurus** [comment]
> Good way to add sidebars is with dictionaries that contains data, but as Django own template language don't allow creating variables, then we need Jinja2 as template engine for this app in order to create variables. This should be added as secondary engine.

No, this problem should be solved with DTL. Jinja is not necessary.

**Comment by kosayoda** [comment]
Issue solved by #417 last year, closing.
