### ISSUE TITLE
Dewikification: Set up redirects for old routes

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#389]
**Remember to target the `dewikification` branch with this pull request**

This will depend on most of the issues in the https://github.com/python-discord/site/projects/1 project, so it should be handled pretty late in the dewikification process.

Most of the issues in the dewikification will probably end up changing the URLs that refer to certain key pages, such as our resources page. This is problematic because many pages on the world wide web refer to our pages, and these will end up being dead URLs.

## So how do we fix that?
Well, currently we have all our pages under the `/pages` path. I propose we create a new django app, `redirect`, which will just be responsible for redirecting these old routes to their new counterparts. e.g., redirecting `pythondiscord.com/pages/resources` to `pythondiscord.com/resources`.

**Comment by swfarnsworth** [comment]
#485 adds many redirects (see [here](https://github.com/python-discord/site/blob/ks129/dewikification/redirection/pydis_site/apps/redirect/redirects.yaml)). Do we know what others might be needed?

**Comment by kosayoda** [comment]
> #485 adds many redirects (see [here](https://github.com/python-discord/site/blob/ks129/dewikification/redirection/pydis_site/apps/redirect/redirects.yaml)). Do we know what others might be needed?

There are, namely the content pages which I am in the process of migrating.

I think other redirects worth considering are shortcuts for some of the regularly visited links, examples being a link like https://pythondiscord.com/rules, which don't lead to anywhere at the moment (canonical link is https://pythondiscord.com/pages/rules).

Additionally, one thing to consider is the current PR uses permanent 301 redirects, which I don't think is a good idea. I'd much rather have it be temporary for an X amount of time just in case there are kinks to resolve.
