### ISSUE TITLE
Get rid of subdomains in our site

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#391]
There is no reason we should use subdomains in our app. Subdomains are a complexity that makes authentication management much more difficult, because OAuth across subdomains does not work well.

## Specification
- Get rid of all subdomain handling. instead of `staff.pythondiscord.com`, we will simply use `pythondiscord.com/staff/`. 
- Get rid of the subdomain dependencies.
- Documentation that refers to subdomains (like the Contributing guide for the bot) may need to be updated. Get someone with access to editing it to help you.
- We will need to update the bot, which specifically uses the subdomains in its configuration. This should just be a matter of changing a few lines in the `default-config.yml` file. Please make sure this change is made, that both pull requests are open at the same time and that they get merged at the same time. We cannot risk downtime of the entire API because of this pull request. Have a core dev or an Admin assist with deployment of this change.

**Comment by jchristgit** [comment]
After reviews are OK on the pull requests, @jb3 needs to perform updates to the Kubernetes deployment.

Per our DM on Discord:

> bot needs to be told to call site.default.svc.cluster.local and append /api onto that
> we don't need a separate DNS record anymore because we're not doing subdomains
> so we can do away with that ingress route and the internal API service

Adding as assignee to keep track of it.
