### ISSUE TITLE
Note on "Using Local Images in Embeds" in discord.py guide

### ISSUE THREAD

**Issue by thomaspet** [python-discord/site#392]
We should add a note on the "Using Local Images in Embeds" section, stating that the filename parameter of discord.File should be the same as the end of the embed url (after attachment://)

Suggested by 609540346304659477 (RaVen) in #discord.py

![bilde](https://user-images.githubusercontent.com/61778143/93203547-e89ae400-f754-11ea-9648-456f297c4131.png)

**Comment by Den4200** [comment]
Updated to be more clear :+1: 

![image](https://user-images.githubusercontent.com/52584399/98587185-c8d8f580-2297-11eb-8e44-d16425464329.png)
