### ISSUE TITLE
User Events Management System

### ISSUE THREAD

**Issue by mbaruh** [python-discord/site#396]
This issue is required for the development of the issue on the bot repo https://github.com/python-discord/bot/issues/1172

The system will require two new tables: `User Events` and `Scheduled Events`

### Fields

* Name (primary key)
* Owner (user ID)
* Subscriptions (many-to-many field of users)

### Operations

* Add a new event record
* Add a user to the subs field
* Query subs by name.
* Remove a user from the subs field
* Remove an event

### Fields

* Event name (foreign key)
* Start time (datetime)
* Duration

### Operations

* Add a new schedule for an event
* Query an event's start time by name
* Remove an event's schedule

**Comment by RohanJnr** [comment]
I am interested in working on this issue along with the bot one.

**Comment by RohanJnr** [comment]
Any reason we are storing the owner's user ID instead of a foreign key to the User model?

**Comment by mbaruh** [comment]
No special reason, I meant it as a foreign key. Feel free to change it to what seems appropriate.

**Comment by RohanJnr** [comment]
will we allow changes in user event names?

**Comment by Akarys42** [comment]
> will we allow changes in user event names?

I'd say yes, I don't see why we shouldn't allow that.

**Comment by RohanJnr** [comment]
> > will we allow changes in user event names?
> 
> I'd say yes, I don't see why we shouldn't allow that.

In that case, the name wouldn't be a good choice for a primary key? cuz when we patch request for updating name, it instead creates a new instance.
We can use the default ID generated by Django.
Lemme do some more testing and get back.
Maybe I can delete the previous instance.

**Comment by Akarys42** [comment]
You can use a UID, no problem, it is better than creating a whole new object and deleting the old one.

**Comment by RohanJnr** [comment]
alright :+1:

**Comment by mbaruh** [comment]
What would be the reasoning behind changing an event name?
If it's just a typo at the moment of creation, they can just delete and make a new one. 
If it's a matter of changing the purpose of the event, I'm not sure we want to allow that. The purpose of having an events table is to allow users to subscribe to them. Users who subscribe to an event about Yu-Gi-Oh! won't want to suddenly find out they're subscribed to an event about the Spice Girls.

Also, even if you use the UID the event name should still be unique. Design-wise, that sounds like it would be more fitting for it to be the primary key.

**Comment by Akarys42** [comment]
Changing an event name doesn't necessarily mean that its purpose changed. I can imagine a lot of situations were the name wouldn't be good enough, and the event owner would just want to change it.

**Comment by mbaruh** [comment]
Still, those kinds of situations sound pretty limited, and I still think the name should be unique. I wouldn't want two events with the same name.

Even if it's not the primary key, it seems that like how change of ownership should only be allowed by an admin, so does changing the name. It seems to me that more often than not a name change would mean that something is up with the event, and a name being changed can confuse the users, so the aim should be to do it as little as possible.

**Comment by Akarys42** [comment]
Fair enough; that said, I think we should even fuzzy match the name to make sure that we don't have any similar already existing events to avoid any trolling.

**Comment by RohanJnr** [comment]
How about also adding in a description field to User Events?

**Comment by mbaruh** [comment]
What function would the description serve?

**Comment by RohanJnr** [comment]
event description. To tell what the event is about.

**Comment by mbaruh** [comment]
I mean, would it be strictly internal for the db / organizer, or do you want to do something with it on the server?

**Comment by RohanJnr** [comment]
It will be displayed in the user events channel

**Comment by mbaruh** [comment]
Yeah, we could do that. Would require an extra field during creation probably. And a way to edit it.

**Comment by RohanJnr** [comment]
With the current implementation on the bot side, the subscriptions field is used as a `write-only` field.

#### The current implementation
The bot adds a reaction on the event message and, reacting the reaction toggles subscription.
During the event start, the reacted users are synced as subscriptions with the site.

#### Conclusion
The subscriptions field can be removed as it does not serve any purpose and the bot can use the reactions on the event message instead.

**Comment by mbaruh** [comment]
That seems fine to me.
Syncing means that even even if it was read, losing all reactions somehow would propogate to the db so just having it stored on the server seems fine, and I don't expect anything to happen to those reactions.
