### ISSUE TITLE
Voice Gate: Enable the metricity database for the site

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#397]
Currently, our site only uses the main site database in our postgres. For the Voice Gate project, we will need to be able to retrieve data from another database in the same postgres server - the `metricity` database.

Django [happily supports multiple databases](https://docs.djangoproject.com/en/3.1/topics/db/multi-db/), so let's take the steps necessary to enable access to this database for the site.

## What you need to do
- Add the database to `settings.py`
- Figure out how this will affect local dev, and make any necessary changes. We will probably need to add a line somewhere so that the metricity database (and maybe some dummy data?) will be added to the local docker postgres, or I imagine it will complain.
- Ensure an appropriate postgres image setup allows for multiple database creation on new deployments, possibly through a single SQL file within `/docker-entrypoint-initdb.d`.

**Comment by jb3** [comment]
Relevant model with the fields that would be present. We will only use a couple of these properties and will most likely use direct SQL instead of tightly integrating with the ORM.

https://github.com/python-discord/metricity/blob/93929d10e20e209a13a6c5c448eed831b6ebbeb7/metricity/models.py#L35-L51

**Comment by scragly** [comment]
The pg docker image has no support for multiple database configs, we'd need to either make use of a startup task/script/sql, or use an alternate image that does support it.

> If you would like to do additional initialization in an image derived from this one, add one or more *.sql, *.sql.gz, or *.sh scripts under /docker-entrypoint-initdb.d (creating the directory if necessary). After the entrypoint calls initdb to create the default postgres user and database, it will run any *.sql files, run any executable *.sh scripts, and source any non-executable *.sh scripts found in that directory to do further initialization before starting the service.

**Comment by lemonsaurus** [comment]
> The pg docker image has no support for multiple database configs, we'd need to either make use of a startup task/script/sql, or use an alternate image that does support it.

What? That doesn't sound right. I'm not talking about multiple instances of the postgres, just databases inside the postgres. Surely it must support this super basic postgres feature? We're just talking about CREATE DATABASE here.

**Comment by jb3** [comment]
No, the postgres docker image only has support for a single database.

You can create other through SQL queries, but the only env vars are `POSTGRES_USER` and `POSTGRES_DB`, for creating a single database.

Scragly's method is the correct one.

**Comment by lemonsaurus** [comment]
What in the world. That's extremely surprising. I guess we need to find an image that isn't some gimped, half-measure version of postgres then. Why are we using an image that doesn't support basic functionality?

**Comment by scragly** [comment]
It's the official image.

**Comment by scragly** [comment]
They also do support it, if you put an SQL with the additional CREATE DATABASE blocks in `/docker-entrypoint-initdb.d`, which is why I mentioned it, it's something that would have to be actually actioned. Just not via config.

**Comment by jb3** [comment]
Creating Docker images based on official ones is common practice, we do it for Hastebin to inject our own configuration.

**Comment by lemonsaurus** [comment]
Okay. So it supports it just fine, it just has to be approached in a particular way. I got a bit worried when you said it doesn't _support_ it, because it sounded like it was the postgres itself that didn't support it, not environment variables or whatever.

Okay yeah, we should add this to the issue specification. Would you mind just editing my OP?

**Comment by scragly** [comment]
Sure. Done.

**Comment by jb3** [comment]
Done.
