### ISSUE TITLE
Voice Gate: Create an API endpoint to retrieve Metricity data.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#398]
**Note: https://github.com/python-discord/site/issues/397 must be resolved before this issue can be started.**

For our Voice Gate project, we need an API that can retrieve certain information stored in the `metricity` database. Specifically, we need `verified_date` and `total_messages` for a specified user, but to make our endpoint more future-proof, we can probably just return all the rows in that table for the specified user.

This will initially be used to improve the `!user` command, and will be used to check if a user qualifies for a speaking role when they try to verify in the voice gate channel.

## Steps
- See the relevant table in metricity [here](https://github.com/python-discord/metricity/blob/93929d10e20e209a13a6c5c448eed831b6ebbeb7/metricity/models.py#L35-L51).
- We will _not_ be using the ORM to get this data. Instead, we're just going to be using raw SQL.
- Do we just return this whole table, or just the specific things we need? Discuss it with us in #dev-contrib or #dev-core.
- When you know you've got this figured out, create a new API endpoint, something like `/users/{uid}/metricity_data`, and just return the relevant data in it.

**Comment by jb3** [comment]
Complete in #409
