### ISSUE TITLE
website profile doesn't 0-pad discord discrims

### ISSUE THREAD

**Issue by ioistired** [python-discord/site#404]
My tag is `lambda#0987` but when I sign in and view my profile, this is what I see 
![screenshot of my profile on pythondiscord.com showing that my username is "lambda#987", not "lambda#0987"](https://user-images.githubusercontent.com/538336/95001061-11f8a400-058c-11eb-84ca-2f568ca6b1d7.png)

**Comment by thomaspet** [comment]
I can probably look at this.

**Comment by Den4200** [comment]
We will be removing OAuth from the site, making this no longer relevant.
