### ISSUE TITLE
Limit results when querying infractions

### ISSUE THREAD

**Issue by Akarys42** [python-discord/site#442]
## Abstract

We had some issues that caused an outage, where someone would search the infractions for single characters, which resulted in an OOM after some time. We need to limit the number of infractions returned by the API

## Proposed Implementation

Add a [`LimitOffsetPagination`](https://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination) to the viewset in `site/pydis_site/apps/api/viewsets/bot/infraction.py`, limiting the output to 50 infractions. 

Note that we need to make sure that Django still won't try to fetch all the infractions in order to sort them, or something similar.

**Comment by ShrillShrestha** [comment]
Hi. I am a beginner and would like to contribute to this project. I am not sure if I fully understood the issue, but it sounds interesting. If you can guide me and provide me with some details I can try to solve the issue. So far, I have looked over the LimitOffsetPagination class and a way to implement it. :)

**Comment by Akarys42** [comment]
Hello @ShrillShrestha, sure thing! If you have any question, feel free to ask in the `#dev-contrib` channel in [our Discord server](discord.gg/python), near the bottom of the list.

**Comment by ShrillShrestha** [comment]
@Akarys42, I was able to run the site in the localhost. Can you tell me how I can reproduce the bug?

**Comment by Akarys42** [comment]
What's your Discord username @ShrillShrestha ? I think it is better if we can talk in the server.

**Comment by ShrillShrestha** [comment]
It is Shrill#5172. I have sent you a request. @Akarys42

**Comment by kunal097** [comment]
Is anyone working on this?

**Comment by jb3** [comment]
It appears @ShrillShrestha seemed to be interested above, but removed their assignment.

@ShrillShrestha do you still want to work on this issue?

**Comment by ShrillShrestha** [comment]
@jb3, I tried doing it, but couldn't figure it out. @kunal097 you can take this.

**Comment by jb3** [comment]
Appreciate the response, go for it @kunal097!

**Comment by mbaruh** [comment]
Hi,
I think the limit should a bit higher than that, like a hundred. We might hit 50 on a few very rare occasions, and I'd rather have some breathing room. The goal is to just not OOM.

**Comment by kunal097** [comment]
Can we have a little discussion about it, like a brief description of the use case and a codebase?

**Comment by HassanAbouelela** [comment]
When querying the database, we should not have it return all found matches, instead 50 or 100 as mentioned. The use case here is that returning all matches with a large DB can cause a memory issue. Searches such as `" "` can return some insanely large number of infractions and cause an OOM error. Akarys was discussing how you can go about testing that feature [here](https://discord.com/channels/267624335836053506/635950537262759947/802257315457794078).

I'm not sure what you mean by codebase, but if you have any specific questions, feel free to ask in the `dev-contrib` channel on the discord server or here.

**Comment by kunal097** [comment]
Is anyone reviewing the changes?

**Comment by Akarys42** [comment]
Don’t worry, we are going to review it. Week-days are a pretty busy time
for me, I’ll make sure to review this this weekend.

**Comment by kunal097** [comment]
Thank you, Actually this is my first contribution so I'm pretty excited.
