### ISSUE TITLE
Group resources by experience level

### ISSUE THREAD

**Issue by jb3** [python-discord/site#449]
We should add functionality to group resources by experience level, for example some of our editors are really suited for beginner programmers and some for advanced, but we have no way of distinguishing that right now.

Each resource in our collection should have a difficulty rating which is one of:
- Beginner
- Intermediate
- Advanced

In particular: The following resources should have difficulty tags: `Read`, `Tools`

This issue supersedes python-discord/meta#49.

**Comment by lemonsaurus** [comment]
I'm closing this in favor of #496, to help prevent confusion. This will be solved by that issue.
