### ISSUE TITLE
Hacktoberfest branding asset link is dead.

### ISSUE THREAD

**Issue by Senjan21** [python-discord/site#452]
Currently, when visiting https://pythondiscord.com/pages/events/ you can't see any logo for *Hacktoberfest* event.
![image](https://user-images.githubusercontent.com/53477086/110361014-bd2bee80-803f-11eb-82e9-3cb5afab72d1.png)

It is due to the fact that structure of branding was changed. Currently we point to `python-discord/branding/master/seasonal/halloween/hacktober/hacktoberfest_animated.gif` 
The `hacktober` folder has since been renamed to `hacktoberfest` and and we have categories per year.

Site should now instead be fetching .gif asset for latest relevant hacktoberfest.

**Comment by whispersofthedawn** [comment]
Can I fix this? It should be a rather simple fix.

**Comment by whispersofthedawn** [comment]
Nevermind, this would have to be fixed by staff or wait until after dewikification

**Comment by doublevcodes** [comment]
I can do this

**Comment by doublevcodes** [comment]
Since the whole events thing is being redone, this can be closed.

**Comment by jb3** [comment]
We won't close it yet, but when a PR is opened to rewrite events put `Closes #452` in the description and this issue will automatically close on merge.

**Comment by whispersofthedawn** [comment]
Should this be replaced with the [animated logo](https://github.com/python-discord/branding/blob/main/events/hacktoberfest/server_icons/animated_server_icon.gif) (what was there before the link went dead) or the [motionless one](https://github.com/python-discord/branding/blob/main/events/hacktoberfest/hacktoberfest/2020/logo.png)? All the others on the events page are motionless.

**Comment by jb3** [comment]
The issue specifies the animated one, and I think we should have the Hacktoberfest branding in there somehow.

**Comment by jbutcher5** [comment]
This hasn't been done yet and I would be able to get this completed. What is this "whole events thing" and does this change the frontend of this page, if so should I hold off?

**Comment by whispersofthedawn** [comment]
The events page is being redesigned as specified in #494, so all the links will be updated then anyway

**Comment by lemonsaurus** [comment]
We're no longer best friends with Hacktoberfest, and will therefore be closing this. (The event is no longer mentioned on our website)
