### ISSUE TITLE
Remove the 100k banner 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/site#453]
Now that we are approaching the 200k members (we are at around 160k at the time of writing), it would be nice to remove the 100k banner. We should still keep the wave and the overall new design brought by @scragly in #415.

The timeline should also be added to the “More” drop down in the navbar. For reference, here is how the site looked before this PR:
![](https://cdn.discordapp.com/attachments/620607373828030464/818150271396872202/unknown.png)

**Comment by scragly** [comment]
I have two largish tasks to complete, so I am unsure on being able to get to this particular task, however I'd be happy to work on it as soon as I'm able to. I'm thinking about a month or so from now. 

There was a 2nd stage semi planned that we never got around to thanks to my recent inactivity, so it would be good to see this actually completed properly.

**Comment by whispersofthedawn** [comment]
I can work on this issue.

**Comment by lemonsaurus** [comment]
I've removed the banner for now, but what @scragly had in mind was far more interesting and we should probably still do that. Meanwhile, the banner is at least gone.
