### ISSUE TITLE
Smarter Resources: Link to GoodReads instead of Amazon.

### ISSUE THREAD

**Issue by GDWR** [python-discord/site#457]
## Updated issue by lemonsaurus
Let's update all our book links to link to GoodReads instead of Amazon. It feels icky to direct all our users to Amazon, but GoodReads is a more neutral destination which links to many different stores.

## Original issue
When on the https://pythondiscord.com/pages/resources/reading/ page, all the links are for the American amazon. 
It is easy enough for a user to find their Amazon-specific, I'm from England so I just change the .com

 amazon.com -> amazon.co.uk  
 
 Not a massive issue, but it may help users from other location than America find the book they can purchase etc.
 There may be more cases than just Book links that this occurs with.

**Comment by GDWR** [comment]
This might be as easy as changing the links to let Amazon redirect etc.

**Comment by HassanAbouelela** [comment]
Does Amazon have a way to create international redirection links? I don't particularly like the idea of having to find the user's country code, replacing it in the URL ourselves, and hoping it doesn't 404. If Amazon doesn't have a way to do it, I think the best next thing is letting the user do it themselves.

**Comment by lemonsaurus** [comment]
Looks like this service would do it:
https://www.booklinker.net/

Doesn't look like Amazon itself has a feature for it. I'm not sure how I feel about using some third party service for this, though.

**Comment by lemonsaurus** [comment]
One thing we could do is link a page like goodreads.com instead of amazon.

**Comment by lemonsaurus** [comment]
Yeah, let's just change our book links to GoodReads. It won't solve the universal link problem, but at least it will link to a bunch of different stores instead of us just sending everyone to Amazon. Feels more neutral and nice.

I've updated the OP with this information.

**Comment by lemonsaurus** [comment]
I'll fix this too while I'm at it.
