### ISSUE TITLE
Django logo is not aligned with baseline of text in the footer

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/site#458]
![bild](https://user-images.githubusercontent.com/1515135/112057846-09cef980-8b17-11eb-8f59-d2fbe31bf999.png)

Here is a close up

![bild](https://user-images.githubusercontent.com/1515135/112058093-629e9200-8b17-11eb-958d-d62140b09758.png)

![bild](https://user-images.githubusercontent.com/1515135/112058261-97aae480-8b17-11eb-8980-38914f18cb0f.png)

The Bulma logo is also a bit off, but it's close enough to not be visible at small sizes I think (I couldn't even notice until I zoomed in to take the screenshots above).

**Comment by MarkKoz** [comment]
Of course the logos use different fonts, but I wonder if it's feasible to adjust their sizes such that the tops of the letters also somewhat align if they don't already.

**Comment by kwzrd** [comment]
Which browser are you using? It doesn't look like that for me in Firefox:

![Screenshot_2021-03-22_22-23-07](https://user-images.githubusercontent.com/44734341/112060507-90a6c500-8b5d-11eb-9073-5d5a9bad9749.png)

Chromium also seems fine. Bulma and Linode still look like they could go lower though.

**Comment by MarkKoz** [comment]
Happens in Firefox on both Windows and Linux. Also happens in Chromium on Windows.

**Comment by MarkKoz** [comment]
It looks fine on Firefox on Android in terms of alignment, but it instead has a different issue.

![Screenshot_20210322-143355_Firefox.jpg](https://user-images.githubusercontent.com/1515135/112061401-b01cfe00-8b1b-11eb-8f30-34b40883cc17.jpg)

**Comment by ChrisLovering** [comment]
Looks similar for me, windows+chromium
![Screenshot 2021-03-22 213406](https://user-images.githubusercontent.com/9753350/112061489-774e4a80-8b56-11eb-878a-0b677dca17e6.png)

**Comment by WMRamadan** [comment]
This problem exists for me on Windows 10 Pro 20H2 using the following browsers:

- Vivaldi: 3.7.2218.45 (Stable channel) (64-bit)
- Brave: Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)
- Google Chrome: Version 92.0.4482.0 (Official Build) canary (64-bit)
- Google Chrome: Version 89.0.4389.128 (Official Build) (64-bit)
- Opera: Version:75.0.3969.171
- Edge: Version 89.0.774.77 (Official build) (64-bit)
- Firefox: 87.0 (64-bit)

**Comment by Shivansh-007** [comment]
Looks perfect for me, Ubuntu20.10 + Firefox Developer Edition

![Screenshot_2021-04-21 Python Discord Home(1)(1)](https://user-images.githubusercontent.com/69356296/115549367-3452d480-a2c6-11eb-9d7e-962a02dd8503.png)

**Comment by WMRamadan** [comment]
Running on Windows 10 Pro 20H2 through WSL2 on Ubuntu 20.04LTS seems to be rending correctly with Firefox 86.0 (64-bit)

**Comment by WMRamadan** [comment]
On macOS Catalina 10.15.7 using the following browsers seems to be correct:

- Google Chrome Version 90.0.4430.72 (Official Build) (x86_64)
- Safari Version 14.0.2 (15610.3.7.1.10, 15610)
- Firefox 80.0.1 (64-bit)

I'm guessing this is an OS specific issue.

<img width="348" alt="Screen Shot 2021-04-24 at 9 52 48 PM" src="https://user-images.githubusercontent.com/1612303/115969798-8c4c3e00-a547-11eb-9253-034fedb617fd.png">
