### ISSUE TITLE
Unexpected 500 error when searching infraction for valid regex

### ISSUE THREAD

**Issue by bast0006** [python-discord/site#463]
Attempting a regex search with `!infraction search "a{3,5}b"` hits the `/bot/infractions/extended` endpoint with `{"search": "a{3,5}b"}`, 

This is a valid regex search, however the site throws a 500 error inside the database, rejecting the regex with:
```
django.db.utils.DataError: invalid regular expression: braces {} not balanced 
```

**Comment by jchristgit** [comment]
I did some digging into this. This is caused by `rest_frameworK` replacing commas with spaces and then splitting the string:
```py
    def get_search_terms(self, request):
        """
        Search terms are set by a ?search=... query parameter,
        and may be comma and/or whitespace delimited.
        """
        params = request.query_params.get(self.search_param, '')
        params = params.replace('\x00', '')  # strip null characters
        params = params.replace(',', ' ')
        return params.split()
```
which results in the following SQL:
```sql
SELECT COUNT(*) AS "__count" FROM "api_infraction" WHERE ("api_infraction"."reason"::text ~* '^James(\s\w+){3' AND "api_infraction"."reason"::text ~* '5}')
```
when our test is modified as follows:
```diff
diff --git a/pydis_site/apps/api/tests/test_infractions.py b/pydis_site/apps/api/tests/test_infractions.py
index 9aae16c0..7b3e2b06 100644
--- a/pydis_site/apps/api/tests/test_infractions.py
+++ b/pydis_site/apps/api/tests/test_infractions.py
@@ -107,7 +107,7 @@ class InfractionTests(APISubdomainTestCase):
 
     def test_filter_search(self):
         url = reverse('bot:infraction-list', host='api')
-        pattern = quote(r'^James(\s\w+){3},')
+        pattern = quote(r'^James(\s\w+){3,5},')
         response = self.client.get(f'{url}?search={pattern}')
 
         self.assertEqual(response.status_code, 200)
```
That said, I'm not sure if this is fixable from our side, nor from `rest_framework`'s side, as this is most likely related to multiple item functionality.

**Comment by jchristgit** [comment]
I will take a second look at it and check whether this is fixed in more recent versions of DRF. If that doesn't work, we're going to close it, as we can't cleanly fix it on our side.

**Comment by jchristgit** [comment]
This is [still the current behaviour in DRF](https://github.com/encode/django-rest-framework/blob/71e6c30034a1dd35a39ca74f86c371713e762c79/rest_framework/filters.py#L67). For what it's worth, somehow working around this in DRF is probably rather tough, but it's not something we can fix on our side.
