### ISSUE TITLE
Build-Your-Own Ducky!

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#465]
Let's make a ducky character creator - like the one on https://lemonsaur.us you ask? Yes. Like that one.

You can choose the color of the duck from a color picker, and you can select accessories to put on it.

To implement this, we'll be using the https://github.com/python-discord/quackstack API. Until Quackstack is ready, this issue is **blocked**.

**Comment by whispersofthedawn** [comment]
Now that quackstack is pretty stable, could I do this after I finish up #494?

**Comment by jb3** [comment]
We should first implement S3 on Quackstack and make sure Quackstack is in a more production ready state, I'll be looking at the former this weekend.

**Comment by lemonsaurus** [comment]
I think now that we have this in Sir Lancebot, I don't think this is necessary anymore.
