### ISSUE TITLE
Add the opt_out field to /bot/users/$id/metricity_data

### ISSUE THREAD

**Issue by Akarys42** [python-discord/site#467]
When a user opt out of metricity, the `opt_out` field is set to True. This field should be returned by the `/bot/users/$id/metricity_data`, which can be achieved by adding `"opt_out"` to

https://github.com/python-discord/site/blob/6d901680b6fc302096a132e1b0e486c12b48d52f/pydis_site/apps/api/models/bot/metricity.py#L34

The following docstring will also have to be modified.

https://github.com/python-discord/site/blob/6d901680b6fc302096a132e1b0e486c12b48d52f/pydis_site/apps/api/viewsets/bot/user.py#L107-L116

**Comment by jb3** [comment]
Resolved by python-discord/metricity#3. We no longer have opt-out functionality.
