### ISSUE TITLE
Datadog Link is Exposed

### ISSUE THREAD

**Issue by robertt** [python-discord/site#48]
I remember a while back I talked to @JoeBanks13 about exposing the DataDog link, and he said no, because of security or something along those lines. When I was looking at the code, I saw there was a file, directly exposing it, and anyone can see it. [Here is a pull request that adds it](https://github.com/discord-python/site/pull/8) 

I know its a minor issue, but still wanted to bring it up, I think there is a way of making it only view able by members, but I dont use DataDog anymore.

**Comment by JoeBanks13** [comment]
Uhm... https://pythondiscord.com/datadog ?

**Comment by JoeBanks13** [comment]
That PR is already merged as well...

**Comment by JoeBanks13** [comment]
Closing this because it's already merged and is in production.

**Comment by gdude2002** [comment]
Joph, you should actually read the issues before responding.

Anyway, I don't see this as a security risk.

**Comment by robertt** [comment]
It was something to do with private user data being released, because you have a metric per user, and you cant expose that.

**Comment by gdude2002** [comment]
There's nothing identifying about those stats.

**Comment by robertt** [comment]
Its what Joseph said when I talked to him about it.
