### ISSUE TITLE
Add Normal Development Workflow to the Contributing page

### ISSUE THREAD

**Issue by whispersofthedawn** [python-discord/site#483]
## Description
I think that it may be useful to add the normal workflow for features and bug fixes to the [Contributing](https://pythondiscord.com/pages/contributing/) page of the site. This would include something that explain how you should first open an issue, wait to get it approved, and only then you should begin developing.

## Reasoning
Many contributors often check the Contributing page and it's subpages to find out what to do when they wish to implement something. This might make it clearer what they should do to avoid wasted time for everyone.

## Additional Details
This is touched on in the [Contributing Guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/) where it says

> **Do not open a pull request if you aren't assigned to the issue.** If someone is already working on it, consider offering to collaborate with that person.

However, that isn't linked anywhere on the contributing pages besides on the [Sir Lancebot](https://pythondiscord.com/pages/contributing/sir-lancebot/) one, and even then, it links through the medium of the [Contributing.md](https://github.com/python-discord/site/blob/main/CONTRIBUTING.md) file which has nothing besides the link to the Contributing Guidelines page.

Also, for people new to open source contribution, the mention on the Contributing Guidelines page may not be clear enough, so I think that outlining the basic workflow on a page that many more people visit could be beneficial.

**Comment by dawnofmidnight** [comment]
Or, the Contributing Guidelines page could be changed to be a little clearer.

**Comment by lemonsaurus** [comment]
This ties into our roadmap issue for this year to make it easier to contribute to our repos. Let's look into this within that context, at some point in 2022.
