### ISSUE TITLE
Allow filtering by resource level

### ISSUE THREAD

**Issue by kosayoda** [python-discord/site#484]
Requires https://github.com/python-discord/site/issues/449.
Once the resources are properly tagged, it would be good to have a filtering system for experience level.

This can be done with a dropdown menu next to each section in each resource.

Here's one such mock implementation:
![image](https://user-images.githubusercontent.com/41782385/117429704-e1318080-af59-11eb-881b-0a6e5a961c56.png)

Anyone who wants to implement this can propose alternative implementations, feel free to do so in `#dev-contrib` or `#dev-dewikification`.

**Comment by lemonsaurus** [comment]
I'm closing this in favor of #496, to help prevent confusion. This will be solved by that issue.
