### ISSUE TITLE
Re-work our main events page

### ISSUE THREAD

**Issue by janine9vn** [python-discord/site#494]
# Proposal
Our current [events page](https://pythondiscord.com/events/) could be improved to draw in more engagement, clearly showcase the upcoming events, and have a stronger call to action for people to join and find the information they're looking for. 

The below image illustrates what I'd like to do.
![EventPage MockUp](https://user-images.githubusercontent.com/20641196/118335723-40edd580-b4de-11eb-9f4d-fda2b82ed6cb.jpg)
- A clear intro blurb briefly describing our events and providing a link to go to the server
- A center showcase of our upcoming events with a strong call-to-action to either join or find out more information
- A nice grid layout of our events with buttons that will either "Show More" info that will pop out a modal that provides more information or a "View Event Page" button that will bring you to a dedicated event page (mostly to be used for the code jams). 
- A nice ToC on the side to give an overview of what there is on the page

These are only ideas though and I'm more than happy with the final design looking different as long as it achieves the following objectives:
- Clear information that can be found via skimming
- Upcoming events are easily found with links for how to join / find out more info
- It's easy to see what events we host and generally when they occur

**Comment by whispersofthedawn** [comment]
I can do this.

**Comment by jbutcher5** [comment]
Is this still being worked on?

**Comment by whispersofthedawn** [comment]
Yes, I'm working on it.

**Comment by doublevcodes** [comment]
Hey @dawnofmidnight are you planning to continue work on this?

**Comment by whispersofthedawn** [comment]
> Hey @dawnofmidnight are you planning to continue work on this?

I am not, no. Would you like to?

**Comment by doublevcodes** [comment]
> > Hey @dawnofmidnight are you planning to continue work on this?
> 
> 
> 
> I am not, no. Would you like to?

Yes, that'd be great 😄

**Comment by jchristgit** [comment]
Hi @doublevcodes, are you still interested in working on this? If not I would put this up for grabs :slightly_smiling_face:
