### ISSUE TITLE
Smarter Resources: Filter by Tag

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#496]
One of the key features in the Smarter Resources project is going to be good filtering. We want to be able to tag all our resources with stuff like difficulty and domain, and then filter by those tags in a clever way.

## How will the filtering work?
Instead of having separate pages for all the different resource types, we'll just have a single page where we display all the resources. This page will allow filtering via GET parameters, so that accessing it with https://pydis.com/resources?type=book will show all the books, and accessing it with https://pydis.com/resources?type=book&price=free will show only the free books.

On this page, we'll show filtering options in a sidebar using checkboxes. Here's an ugly mockup:
![image](https://user-images.githubusercontent.com/2098517/118357569-169e2580-b57b-11eb-844a-b74ac6b7171f.png)

**This page should be reactive**, so that clicking on one of these checkboxes immediately changes the contents displayed on the page. We may need to use something like https://htmx.org/ to pull that off, but the user experience is going to be much much better, so we should make the effort.

## Which tags do we need?
Initially, we'll tag our resources with one of each of the following tags. **Note that part of this issue will be working through all existing resources and assigning tags to them**.

#### Resource type
- Book
- Guide
- Course
- Interactive
- Video
- Podcast
- Tool
- Community

#### Difficulty
- Beginner
- Intermediate
- Expert

#### Price model
- Free
- Paid
- Subscription

#### Domain
- Web Development
- Data Science

## What about that beautiful categories page we currently have?
You mean this page?
![image](https://user-images.githubusercontent.com/2098517/118357659-9d530280-b57b-11eb-8d3c-196a0818bbb5.png)

**I think we should get rid of this page, save our users an additional click.**

## Related issues
Resolves https://github.com/python-discord/site/issues/484
Resolves https://github.com/python-discord/site/issues/449

**Comment by jb3** [comment]
A couple of thoughts:
- The word `Topic` is better than domain.
- Topic/Domain probably cannot be a list like shown in the mockup, if we want it to be truly scalable we need a better way to present that than a huge list of checkboxes. Maybe a search of some for topic areas, though I'm not entirely sure.

**Comment by lemonsaurus** [comment]
I agree that Topic is better than domain, let's do that instead.

however, I'm confused by your scalability comment. how many topics are you really expecting here? I was not expecting to scale that at all.

**Comment by jb3** [comment]
One of the major points behind this system was so we could add topics that were too specific. We've talked about having stuff like individual libraries such as `discord.py` as topics where we've rejected resource suggestions because they were too specific.

**Comment by lemonsaurus** [comment]
okay, so, if we get into a situation where we have a lot of topic tags, we can show the 5 topics with the most resources in them, and then a button like "show all topics" that brings up a modal with the rest.

**Comment by lemonsaurus** [comment]
I think I'd like to build this myself while I got some time off this week. Self-assigning.

**Comment by lemonsaurus** [comment]
This has been solved in #570
