### ISSUE TITLE
Move command line instructions above PyCharm in guides

### ISSUE THREAD

**Issue by whispersofthedawn** [python-discord/site#509]
On various guides on the site such as the one on [Installing Project Dependencies](https://pythondiscord.com/pages/guides/pydis-guides/contributing/installing-project-dependencies/), you find the command line instructions at the very bottom of the page, below the (rather space consuming) guides for PyCharm.

On pages filled with images, it can be easy to miss the command line instructions for very important steps. Plus, it's likely that more people will use the command line instructions, since Python programmers use a large variety of editors/IDEs. I think it would be beneficial to move the command line instructions to the tops of these pages so that people will be able to find them easily.

Some pages that have this:
- https://pythondiscord.com/pages/guides/pydis-guides/contributing/cloning-repository/
- https://pythondiscord.com/pages/guides/pydis-guides/contributing/installing-project-dependencies/

**Comment by soham4abc** [comment]
Working on this

**Comment by whispersofthedawn** [comment]
Generally, you should probably wait until this is approved by a staff member. You shouldn't start it yet, as it might go to waste if it's not approved.

**Comment by soham4abc** [comment]
Okie dokie. Waiting for approval, Once approved you can assign me if possible.. Willing to work on this issue

**Comment by soham4abc** [comment]
Is this issue not yet approved? @dawnofmidnight

**Comment by kosayoda** [comment]
@soham4abc Consider it approved. Go for it!

**Comment by soham4abc** [comment]
> @soham4abc Consider it approved. Go for it!

Thank you !!
