### ISSUE TITLE
Add information about help channel DM service command to help channel guide

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/site#537]
We recently added a command, `!helpdm on`, to the bot that allows users to enable notifications for the help channel of others that they are active in. However, the command is currently only mentioned in a `#changelog` entry, which scrolls out of view rather quickly.

@MarkKoz suggested that we should add it to the [help channel guide](https://www.pythondiscord.com/pages/guides/pydis-guides/help-channel-guide/), which is a good idea.

**Comment by jchristgit** [comment]
@minalike will take care of this in #624
