### ISSUE TITLE
Only three off-topic channels?

### ISSUE THREAD

**Issue by tschutter** [python-discord/site#548]
In the [Conversation Etiquette in Our Off-Topic Channels](https://pythondiscord.com/pages/guides/pydis-guides/off-topic-etiquette/) page, it says that there are "three off-topic channels".  The current count seems to be about 43.  I would suggest "dozens of off-topic channels" or "many off-topic channels" instead.

**Comment by Akarys42** [comment]
Are you talking about topical channels? Off-topic channels are the ones generally under the discussion category (currently under the code jam), in a category itself called `OFF-TOPIC / GENERAL`. There are currently only three of them.

**Comment by ToxicKidz** [comment]
Are you thinking of our help channels? We definitely have 3 off topic channels
![Screenshot_2021-06-30-11-28-21-1.png](https://user-images.githubusercontent.com/78174417/123988954-723f3980-d996-11eb-8719-cc50fdf47ca6.png)

**Comment by tschutter** [comment]
Ooops.  My bad.  I had seen the "topical chat/help" channels, and so I then translated the "help channels" in my head to be "off-topic help channels".  Nothing to see here.  Move along.  Closing.
