### ISSUE TITLE
Monthly Data Reviews Link Missing

### ISSUE THREAD

**Issue by ethansocal** [python-discord/site#564]
The link to monthly data reviews on the timeline doesn't exist anymore. https://github.com/python-discord/site/blob/93be3f40a07f988d63cacb2dc24ca35c17fee76a/pydis_site/templates/home/timeline.html#L114

**Comment by ChrisLovering** [comment]
new link is `https://www.notion.so/6784e3a9752444e89d19e65fd4510d8d?v=69268794b9d2454a9c28e1550e2923c2` for anyone who wants to make this change

**Comment by ethansocal** [comment]
Could I make this change and open a pull request?

**Comment by ChrisLovering** [comment]
Sure! I've assigned you to the issue too.
