### ISSUE TITLE
Add an endpoint to fetch user information from a username.

### ISSUE THREAD

**Issue by Qwerty-133** [python-discord/site#578]
We'd need this endpoint to be able to implement features requested in [this](https://github.com/python-discord/bot/issues/1757) bot issue.

```py
from django.shortcuts import get_object_or_404

    @action(
        detail=False,
        methods=["GET"],
        url_path=r"username/(?P<name>[^#]{,32})#(?P<discriminator>[0-9]{4})"
    )
    def get_by_username(self, request, name, discriminator):
        user = get_object_or_404(User, name=name, discriminator=discriminator)
        return Response(UserSerializer(user).data, status=status.HTTP_200_OK)
```

This addition to the user view set seems to make GET requests to URLs like `bot/users/username/Qwerty#0001` work , but there might be a more ideal way to do this.

**Comment by mbaruh** [comment]
I realized that the infractions viewset allows filtering by fields.

Adding:
```py
filter_backends = (DjangoFilterBackend,)
filter_fields = ('name', 'discriminator')
```
To `UserViewSet` and then calling
```py
await ctx.bot.api_client.get("bot/users", params=dict(name="Qwerty", discriminator=1))
```
Allowed fetching the user data by name and discriminator.

I think the implementation of this is simpler, but it returns a nested dictionary with a list of user dictionaries under "results".
I'm fine with either approach, but someone else might have a stronger opinion.

**Comment by mbaruh** [comment]
It's probably possible to retrieve it as a simple list as the infractions endpoint does, but this is where my superficial django knowledge ends.

EDIT: Courtesy of @ChrisLovering, it's done with `pagination_class = LimitOffsetPaginationExtended`

**Comment by Kronifer** [comment]
Wouldn't this be more appropriate for python-discord/API?

**Comment by Qwerty-133** [comment]
> Wouldn't this be more appropriate for python-discord/API?

We don't have an "API" repository, and this is a site endpoint for which code would need to be added in this repository.

**Comment by Kronifer** [comment]
> 
> 
> 
> > Wouldn't this be more appropriate for python-discord/API?
> 
> We don't have an "API" repository, and this is a site endpoint for which code would need to be added in this repository.

https://github.com/python-discord/api

**Comment by mbaruh** [comment]
@Kronifer The new API is not live at the moment, and there's no feature freeze on this repo.

**Comment by jchristgit** [comment]
I agree with the approach suggested by @mbaruh. Reusing DRF's builtin logic for this allows us to keep custom code (including tests, docs, etc.) to a minimum.
