### ISSUE TITLE
The Sub-Articles button is broken on mobile 

### ISSUE THREAD

**Issue by Akarys42** [python-discord/site#643]
Clicking the button simply doesn't do anything

Device information:
![Screenshot_20220120-123436](https://user-images.githubusercontent.com/44778521/150331392-78c5005c-a4ce-49b0-ae3c-d1f6eeec278a.png)

**Comment by ChrisLovering** [comment]
Which page is this button on?

**Comment by ChrisLovering** [comment]
@Akarys42 Could you please specify which button you are referring to.

**Comment by Akarys42** [comment]
![Screenshot_20220124-175047](https://user-images.githubusercontent.com/44778521/150864536-d8446a19-f9e1-4c34-bf1d-85b323fcfdad.png)
This one
