### ISSUE TITLE
Multiple jams pages

### ISSUE THREAD

**Issue by kovaceviccz** [python-discord/site#80]
Code-jam page can now be found at: https://pythondiscord.com/jams as mentioned in the latest jam announcement in discord. Now the [wiki jams page](https://wiki.pythondiscord.com/wiki/jams) returns a weird 404, showing the [PageView](https://github.com/discord-python/site/blob/master/pysite/views/wiki/page.py#L9) class.

The wiki page should be either removed or redirect to jams for past references.

**Comment by gdude2002** [comment]
Not an issue. That page isn't a 404, it's a "we'll make this soon". We do plan to put more information there, when we get around to it - the `/jams` route on the main site isn't a knowledgebase.
